from pathlib import Path
from playwright.sync_api import sync_playwright
import json,math,time,os,argparse
ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(description='Exercise the portable Vanta Forge editor and game in Chromium.')
parser.add_argument('--browser',default=os.environ.get('CHROME_BIN'),help='Optional Chromium executable path; otherwise use Playwright Chromium.')
parser.add_argument('--url',help='Optional served portable-editor URL; default is an offline about:blank content harness.')
parser.add_argument('--software',action='store_true',help='Request the SwiftShader WebGL backend for headless CI.')
args=parser.parse_args()
OUTPUT=ROOT/'docs'/'test-artifacts'
OUTPUT.mkdir(parents=True,exist_ok=True)
def load_editor(page):
    if args.url: page.goto(args.url,wait_until='load')
    else: page.set_content((ROOT/'vanta-forge.html').read_text(),wait_until='load')
results=[]
def check(name,condition,detail=None):
    assert condition,f'{name}: {detail}'
    results.append({'test':name,'passed':True,'detail':detail})
    print('PASS',name,detail or '',flush=True)
with sync_playwright() as p:
    options={'headless':True}
    if args.browser: options['executable_path']=args.browser
    if args.software: options['args']=['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']
    browser=p.chromium.launch(**options)
    page=browser.new_page(viewport={'width':1440,'height':960},device_scale_factor=1)
    page.set_default_timeout(30000)
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('dialog',lambda d:d.accept('PF_TestActor') if d.type=='prompt' else d.accept())
    load_editor(page)
    page.wait_for_function('!!window.vanta?.renderer.name && document.querySelector("#loading").hidden')
    page.wait_for_timeout(700)
    editor_backend=page.evaluate('vanta.renderer.name')
    check('Browser initializes a real graphics renderer',editor_backend in ('WebGPU','WebGL2 fallback'),editor_backend)
    page.evaluate('vanta.running=false')
    page.screenshot(path=str(OUTPUT/'editor.png'))
    base=page.evaluate('vanta.scene.data.entities.length')
    page.locator('[data-place="cube"]').dblclick()
    check('Actor palette creates an actual scene entity',page.evaluate('vanta.scene.data.entities.length')==base+1)
    actor_id=page.evaluate('vanta.selection')
    page.locator('[data-prop="transform.position.0"]').fill('3.75')
    page.locator('[data-prop="transform.position.0"]').press('Tab')
    check('Property inspector changes transform',page.evaluate('vanta.scene.get(vanta.selection).transform.position[0]')==3.75)
    page.locator('[data-menu="edit"]').click();page.locator('#menuPopup [data-action="undo"]').click()
    check('Undo restores prior transform',page.evaluate('vanta.scene.get(vanta.selection).transform.position[0]')!=3.75)
    page.locator('[data-menu="edit"]').click();page.locator('#menuPopup [data-action="redo"]').click()
    check('Redo reapplies transform',page.evaluate('vanta.scene.get(vanta.selection).transform.position[0]')==3.75)
    h=page.evaluate('''()=>{vanta.renderer.render(vanta.scene,vanta.assets,vanta.camera,vanta.selection);vanta.drawOverlay();const h=vanta.gizmoHandles[0],r=document.querySelector('#overlayCanvas').getBoundingClientRect();return {x:r.left+h.center[0]+h.dx*.7,y:r.top+h.center[1]+h.dy*.7,dx:h.dx*.3,dy:h.dy*.3};}''')
    page.mouse.move(h['x'],h['y']);page.mouse.down();page.mouse.move(h['x']+h['dx'],h['y']+h['dy'],steps=3);page.mouse.up()
    check('Viewport gizmo pointer drag modifies geometry transform',page.evaluate('vanta.scene.get(vanta.selection).transform.position[0]')!=3.75)
    page.locator('[data-bottom="graph"]').click()
    page.wait_for_timeout(200)
    count=page.locator('.graph-node').count()
    page.locator('#nodeSelect').select_option('Number');page.locator('[data-action="add-node"]').click()
    check('Visual graph creates an executable typed node',page.locator('.graph-node').count()==count+1)
    node=page.locator('.graph-node.value [data-param="value"]').last
    node.fill('42');node.press('Tab')
    check('Graph node parameter editor writes the graph asset',page.evaluate('vanta.graphUI.graph.nodes.at(-1).params.value')==42)
    page.locator('.graph-node.value [data-delete-node]').last.click()
    page.locator('#graphWires [data-edge="0"]').dispatch_event('click')
    check('Clicking a wire disconnects it',page.evaluate('vanta.graphUI.graph.edges.length')==2)
    page.locator('.node-port.output[data-node="overlap"][data-port="exec"]').click()
    page.locator('.node-port.input[data-node="score"][data-port="exec"]').click()
    check('Typed port interaction reconnects executable graph',page.evaluate('vanta.graphUI.graph.edges.length')==3)
    page.locator('[data-action="compile-graph"]').click()
    check('Graph compilation validates edited graph',page.evaluate('vanta.graphUI.status().length')==0)
    page.evaluate('vanta.graphUI.render();vanta.renderer.render(vanta.scene,vanta.assets,vanta.camera,vanta.selection);vanta.drawOverlay()')
    page.wait_for_timeout(150)
    page.screenshot(path=str(OUTPUT/'graph.png'))
    page.locator('[data-bottom="content"]').click()
    before=page.evaluate('JSON.stringify(vanta.scene.serialize())')
    page.locator('#playButton').click()
    check('Play button creates separate runtime',page.evaluate('!!vanta.runtime&&vanta.runtime.scene!==vanta.scene'))
    start=page.evaluate('vanta.runtime.player.transform.position.slice()')
    page.keyboard.down('KeyW');page.evaluate('()=>{for(let i=0;i<100;i++)vanta.runtime.step()}');page.keyboard.up('KeyW')
    end=page.evaluate('vanta.runtime.player.transform.position.slice()')
    check('Real keyboard input moves the physics-controlled player',math.dist(start,end)>1,{'distance':round(math.dist(start,end),3)})
    page.locator('#pauseButton').click();tick=page.evaluate('vanta.runtime.tick')
    page.locator('#stepButton').click()
    check('Single-step advances exactly one deterministic tick',page.evaluate('vanta.runtime.tick')==tick+1)
    page.evaluate('''()=>{const g=vanta.runtime;for(const s of g.scene.data.entities.filter(e=>e.components.collectible)){g.player.transform.position=s.transform.position.slice();g.player.components.body.velocity=[0,0,0];g.scene.invalidate();g.step();}g.follow(1);vanta.renderer.render(g.scene,g.assets,g.camera);vanta.drawOverlay();}''')
    check('Game physics triggers run score and destroy graph actions',page.evaluate('vanta.runtime.score')==6)
    check('Runtime HUD reflects executable gameplay results',page.locator('#gameScore').inner_text()=='6 / 6')
    page.screenshot(path=str(OUTPUT/'play.png'))
    page.keyboard.press('Escape')
    check('Stopping Play restores unmodified authoring scene',page.evaluate('JSON.stringify(vanta.scene.serialize())')==before)
    page.evaluate('vanta.select('+json.dumps(actor_id)+')')
    prefabs=page.evaluate('Object.keys(vanta.scene.data.assets.prefabs).length')
    page.locator('[data-action="save-prefab"]').click()
    check('Create prefab stores reusable entity payload',page.evaluate('Object.keys(vanta.scene.data.assets.prefabs).length')==prefabs+1)
    count=page.evaluate('vanta.scene.data.entities.length')
    page.locator('.asset-card.prefabs').filter(has_text='PF_TestActor').dblclick()
    check('Prefab instantiation adds a new entity with stable new ID',page.evaluate('vanta.scene.data.entities.length')==count+1)
    count=page.evaluate('Object.keys(vanta.scene.data.assets.meshes).length')
    page.locator('#fileInput').set_input_files({'name':'triangle.obj','mimeType':'text/plain','buffer':b'v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n'})
    page.wait_for_function('Object.keys(vanta.scene.data.assets.meshes).length>'+str(count))
    check('OBJ import executes in asset worker and registers geometry',page.evaluate('Object.values(vanta.scene.data.assets.meshes).at(-1).indices.length')==3)
    page.evaluate('vanta.setTool("terrain");vanta.brushPoint=[20,0,0]')
    original=page.evaluate('vanta.scene.data.assets.terrain.heights.slice()')
    # First validate the heightfield transaction, then exercise the actual brush pointer path.
    page.evaluate('vanta.commit("Test landscape",()=>{const t=vanta.scene.data.assets.terrain;t.heights[0]+=1;t.version++})')
    check('Terrain editing updates stored heightfield',page.evaluate('vanta.scene.data.assets.terrain.heights[0]')!=original[0])
    page.evaluate('vanta.undo()')
    check('Terrain edit is undoable',page.evaluate('vanta.scene.data.assets.terrain.heights')==original)
    page.evaluate('vanta.camera.target=[20,0,0];vanta.camera.distance=20;vanta.camera.orbit();vanta.renderer.render(vanta.scene,vanta.assets,vanta.camera,vanta.selection);vanta.drawOverlay()')
    terrain_before=page.evaluate('vanta.scene.data.assets.terrain.heights.slice()')
    bounds=page.locator('#overlayCanvas').bounding_box()
    cx=bounds['x']+bounds['width']*.5;cy=bounds['y']+bounds['height']*.55
    page.mouse.move(cx,cy);page.mouse.down();page.mouse.move(cx+15,cy+5,steps=3);page.mouse.up()
    check('Actual viewport brush stroke modifies landscape heights',page.evaluate('vanta.scene.data.assets.terrain.heights')!=terrain_before)
    page.evaluate('vanta.undo()')
    check('A complete pointer-driven landscape stroke undoes atomically',page.evaluate('vanta.scene.data.assets.terrain.heights')==terrain_before)
    # Export a clean demonstration, rather than the temporary test edits.
    # The original portable app can be reconstructed by reloading its content without network navigation.
    clean=browser.new_page(viewport={'width':1280,'height':800},device_scale_factor=1)
    clean.on('pageerror',lambda e:errors.append(str(e)))
    load_editor(clean)
    clean.wait_for_function('!!window.vanta?.renderer.name && document.querySelector("#loading").hidden')
    clean.evaluate('vanta.running=false')
    html=clean.evaluate('vanta.exportGame()')
    check('Export returns a self-contained HTML runtime',html is not None and 'scene-data' in html and 'VantaRuntime.launchStandalone' in html)
    (ROOT/'aether-relay-game.html').write_text(html)
    game=browser.new_page(viewport={'width':1280,'height':800},device_scale_factor=1)
    game.on('pageerror',lambda e:errors.append(str(e)))
    game.set_content(html,wait_until='load');game.wait_for_function('!!window.vantaGame')
    check('Exported game starts independently without editor code',game.evaluate('!!vantaGame.runtime && !window.vanta'))
    check('Exported game uses real graphics backend',game.evaluate('vantaGame.renderer.name') in ('WebGPU','WebGL2 fallback'))
    game.evaluate('''()=>{const g=vantaGame.runtime;g.paused=true;for(const s of g.scene.data.entities.filter(e=>e.components.collectible)){g.player.transform.position=s.transform.position.slice();g.player.components.body.velocity=[0,0,0];g.scene.invalidate();g.step();}}''')
    check('Exported game executes the same collectible logic',game.evaluate('vantaGame.runtime.score')==6)
    mobile=browser.new_page(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True)
    mobile.on('pageerror',lambda e:errors.append(str(e)))
    mobile.set_content(html,wait_until='load');mobile.wait_for_function('!!window.vantaGame')
    mobile.evaluate('vantaGame.runtime.paused=true')
    check('Standalone touch controls appear on a narrow coarse-pointer viewport',mobile.locator('[data-key="KeyW"]').is_visible())
    before_touch=mobile.evaluate('vantaGame.runtime.player.transform.position.slice()')
    btn=mobile.locator('[data-key="KeyW"]').bounding_box()
    mobile.mouse.move(btn['x']+btn['width']/2,btn['y']+btn['height']/2);mobile.mouse.down()
    mobile.evaluate('()=>{for(let i=0;i<80;i++)vantaGame.runtime.step()}');mobile.mouse.up()
    after_touch=mobile.evaluate('vantaGame.runtime.player.transform.position.slice()')
    check('On-screen movement button drives the actual player controller',math.dist(before_touch,after_touch)>.5)
    check('No uncaught JavaScript exceptions during browser workflow' ,len(errors)==0,errors)
    browser.close()
(ROOT/'docs'/'browser-test-results.json').write_text(json.dumps({'backend':editor_backend,'harness':args.url or 'Portable HTML injected into about:blank','nativeWebGPU':editor_backend=='WebGPU','indexedDB':'Not covered by this suite; about:blank has an opaque origin','tests':results},indent=2))
print(len(results),'browser checks passed',flush=True)
