import {Scene,History,ProjectStore,entity,uid,validateScene,translateEntity} from './scene.js';
import {Assets,importOBJ,createTerrain,sculptTerrain,intersectMesh} from './assets.js';
import {Renderer} from './renderer.js';
import {Camera,GameRuntime,InputState} from './runtime.js';
import {createDemo} from './demo.js';
import {NODE_TYPES,graphNode,validateGraph} from './graph.js';
import {$,esc,icon,applyIcons,entityIcon,InspectorUI,GraphUI} from './editor-ui.js';
import {clamp,rad,deg,point,direction,inverse,compose,mmul,vadd,vsub,vmul,vnorm,vdot,vcross,vlength,boundsTransform,screenPoint,cameraRay,rayBox,deepCopy} from './math.js';
export function downloadFile(name,contents,type='application/json'){const blob=contents instanceof Blob?contents:new Blob([contents],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function decomposeTransform(m){const scale=[Math.hypot(m[0],m[1],m[2]),Math.hypot(m[4],m[5],m[6]),Math.hypot(m[8],m[9],m[10])],y=Math.asin(clamp(-m[2]/scale[0],-1,1));let x,z;if(Math.abs(Math.cos(y))>1e-5){x=Math.atan2(m[6]/scale[1],m[10]/scale[2]);z=Math.atan2(m[1]/scale[0],m[0]/scale[0]);}else{x=0;z=Math.atan2(-m[4]/scale[1],m[5]/scale[1]);}return {position:[m[12],m[13],m[14]],rotation:[deg(x),deg(y),deg(z)],scale};}
export class ForgeEditor {
  constructor(){this.scene=new Scene(createDemo());this.assets=new Assets(this.scene.data.assets);this.history=new History();this.camera=new Camera();this.input=new InputState();this.selection=this.scene.data.entities.find(e=>e.name==='Ion field · core ring').id;this.tool='move';this.snap=false;this.colliders=false;this.filter='all';this.bottom='content';this.brushRadius=4;this.brushStrength=.18;this.graphUI=new GraphUI(this);this.inspector=new InspectorUI(this);this.folded=new Set();this.logs=[];this.dirty=false;this.previewScene=null;this.previewTime=0;this.animationTrack=0;this.gizmoHandles=[];this.running=true;this.renderer=new Renderer($('#renderCanvas'),m=>this.log('warn',m));}
  async start(){applyIcons();this.bindUI();this.refresh();this.log('info','Vanta Forge 1.0 · editor initialized');const forceGL=new URLSearchParams(location.search).has('webgl');try{await this.renderer.init(forceGL);$('#backendBadge').innerHTML='<i></i> '+this.renderer.name.toUpperCase();$('#loading').hidden=true;$('#statusText').textContent='Ready';this.log('info',`${this.renderer.name} · PBR, 4× MSAA (WebGPU), shadow pass, instancing, frustum culling`);}catch(e){$('#loading').classList.add('failed');$('#loading strong').textContent='Renderer unavailable';$('#loading span').textContent=e.message;this.log('error',e.message);throw e;}
    try{if(!new URLSearchParams(location.search).has('fresh')){const stored=await ProjectStore.load();if(stored){this.scene=new Scene(stored);this.assets=new Assets(this.scene.data.assets);this.selection=null;this.refresh();this.log('info','Recovered locally saved project from IndexedDB');}}}catch(e){this.log('warn','Local persistence: '+e.message);}
    this.bindViewport();this.lastFrame=performance.now();this.statsTime=this.lastFrame;this.frameCount=0;requestAnimationFrame(now=>this.frame(now));this.toast('Aether Relay is ready. Press Play to explore.');}
  meshList(){return [{id:'cube',name:'SM_Cube'},{id:'sphere',name:'SM_Sphere'},{id:'cylinder',name:'SM_Cylinder'},{id:'torus',name:'SM_Ring'},{id:'crystal',name:'SM_EnergyShard'},{id:'terrain',name:'SM_Landscape'},...Object.entries(this.scene.data.assets.meshes).map(([id,m])=>({id,name:m.name||id}))];}
  get activeScene(){return this.runtime?.scene||this.previewScene?.scene||this.scene;}
  toast(message,error=false){const el=$('#toast');el.textContent=message;el.classList.toggle('error',error);el.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.remove('show'),3600);}
  log(level,message){const entry={level,message:String(message),time:new Date().toLocaleTimeString('en-GB')};this.logs.push(entry);if(this.logs.length>400)this.logs.shift();$('#logBadge').textContent=this.logs.filter(l=>l.level!=='info').length||'';this.renderLog();if(level==='error')this.toast(message,true);}
  renderLog(){const list=$('#logList');list.innerHTML=this.logs.map(e=>`<div class="log-line ${e.level}"><time>${e.time}</time><span>${esc(e.message)}</span></div>`).join('');list.scrollTop=list.scrollHeight;}
  commit(label,mutate){if(this.runtime){this.toast('Stop Play mode before editing the source scene');return false;}const before=this.scene.serialize();try{mutate();validateScene(this.scene.data);this.scene.reindex();this.previewScene=null;this.finishEdit(before,label);return true;}catch(e){this.scene=new Scene(before);this.assets=new Assets(this.scene.data.assets);this.refresh();this.toast(e.message,true);this.log('warn',label+': '+e.message);return false;}}
  finishEdit(before,label,refresh=true){if(this.history.record(before,this.scene.serialize(),label)){this.dirty=true;this.scene.invalidate();this.previewScene=null;$('#dirtyMark').style.visibility='visible';$('#saveState').textContent='Unsaved changes';$('#statusText').textContent=label;this.scheduleSave();}if(refresh)this.refresh();}
  scheduleSave(){clearTimeout(this.autosaveTimer);this.autosaveTimer=setTimeout(()=>this.save(false),1200);}
  async save(notify=true){try{await ProjectStore.save(this.scene.serialize());this.dirty=false;$('#dirtyMark').style.visibility='hidden';$('#saveState').textContent='All changes saved';$('#statusText').textContent='Saved locally';if(notify)this.toast('Project saved to local IndexedDB');}catch(e){$('#saveState').textContent='Save failed';this.log('warn','IndexedDB save failed: '+e.message);if(notify)this.toast('Local save unavailable. Use File → Download project.',true);}}
  replace(data,label='Load project'){this.stop();this.scene=new Scene(validateScene(data));this.assets=new Assets(this.scene.data.assets);this.selection=null;this.previewScene=null;this.history.clear();this.camera=new Camera();this.refresh();this.scheduleSave();this.log('info',label+': '+data.name);}
  undo(){if(this.runtime)return;const data=this.history.undo();if(!data){this.toast('Nothing to undo');return;}this.scene=new Scene(data);this.assets=new Assets(data.assets);this.previewScene=null;this.refresh();this.scheduleSave();this.toast('Undo complete');}
  redo(){if(this.runtime)return;const data=this.history.redo();if(!data){this.toast('Nothing to redo');return;}this.scene=new Scene(data);this.assets=new Assets(data.assets);this.previewScene=null;this.refresh();this.scheduleSave();this.toast('Redo complete');}
  refresh(){if(this.selection&&!this.scene.get(this.selection)&&!this.runtime?.scene.get(this.selection))this.selection=null;$('#projectName').textContent=this.scene.data.name;document.title=`Vanta Forge — ${this.scene.data.name}`;this.renderOutliner();this.inspector.render();this.renderAssets();this.renderPlace();this.graphUI.render();applyIcons($('.toolbar'));}
  select(id){this.selection=id;this.animationTrack=0;this.previewScene=null;this.renderOutliner();this.inspector.render();const e=this.activeScene.get(id);$('#statusText').textContent=e?'Selected '+e.name:'Ready';if(e?.components.graph&&this.bottom==='graph'){this.graphUI.graphId=e.components.graph.asset;this.graphUI.render();}}
  setTool(tool){if(this.runtime)return;this.tool=tool;for(const b of document.querySelectorAll('[data-tool]'))b.classList.toggle('active',b.dataset.tool===tool);if(tool==='terrain'){const e=this.scene.data.entities.find(e=>e.components.mesh?.asset==='terrain');if(e)this.select(e.id);this.toast('Drag to raise terrain. Hold Shift to lower.');$('#viewportHint').textContent='Drag raise · Shift lower · RMB orbit · Scroll zoom';}else $('#viewportHint').innerHTML='RMB orbit <i>·</i> MMB pan <i>·</i> Scroll zoom <i>·</i> F focus';}
  renderPlace(){const query=$('#placeSearch').value.toLowerCase(),shapes=[['cube','Cube','Static mesh'],['sphere','Sphere','Static mesh'],['cylinder','Cylinder','Static mesh'],['torus','Ring','Static mesh'],['crystal','Crystal','Static mesh']],systems=[['light','Point Light','Lighting'],['body','Physics Body','Dynamic rigid body'],['player','Player Start','Character controller'],['terrain','Landscape','Sculptable heightfield']];const render=(items,system)=>items.filter(([,n])=>n.toLowerCase().includes(query)).map(([kind,name,desc])=>`<div class="place-item ${system?'system':''}" data-place="${kind}" draggable="true"><div class="place-icon">${icon(kind)}</div><div><strong>${name}</strong><small>${desc}</small></div></div>`).join('');$('#placeActors').innerHTML=render(shapes,false);$('#placeSystems').innerHTML=render(systems,true);}
  renderOutliner(){const scene=this.activeScene,query=$('#outlinerSearch').value.toLowerCase(),entities=scene.data.entities;$('#actorCount').textContent=entities.length;$('#objectStats').textContent=entities.length+' actors';let html='';const draw=(e,depth)=>{const children=entities.filter(c=>c.parent===e.id),matches=e.name.toLowerCase().includes(query);if(query&&!matches&&!children.some(c=>c.name.toLowerCase().includes(query)))return;const type=e.components.player?'Player':e.components.light?'Light':e.components.graph?'Graph':e.components.mesh?.asset==='terrain'?'Terrain':e.components.body?.type==='dynamic'?'Physics':e.components.mesh?'Mesh':'Group';html+=`<div class="tree-row ${e.id===this.selection?'selected':''} ${e.visible===false?'hidden-actor':''}" data-entity="${esc(e.id)}" role="treeitem" aria-selected="${e.id===this.selection}" style="padding-left:${6+depth*12}px"><span class="tree-arrow" data-fold="${esc(e.id)}">${children.length?this.folded.has(e.id)?'▸':'▾':''}</span><span class="tree-icon">${icon(entityIcon(e))}</span><span class="tree-name">${esc(e.name)}</span><span class="tree-type">${type}</span><button class="eye-toggle" data-visibility="${esc(e.id)}" title="Toggle visibility">${e.visible===false?'○':'◦'}</button></div>`;if(!this.folded.has(e.id)||query)children.forEach(c=>draw(c,depth+1));};entities.filter(e=>!e.parent).forEach(e=>draw(e,0));$('#outlinerTree').innerHTML=html;$('#selectionLabel').textContent=this.selection?scene.get(this.selection)?.name||'No actor selected':`${entities.length} actors in world`;}
  renderAssets(){const assets=this.scene.data.assets,list=[...this.meshList().map(m=>({...m,type:'meshes',icon:m.id in {cube:1,sphere:1,cylinder:1,torus:1,crystal:1,terrain:1}?m.id:'cube'})),...Object.entries(assets.materials).map(([id,m])=>({id,name:m.name,type:'materials',color:m.color})),...Object.entries(assets.prefabs).map(([id,p])=>({id,name:p.name,type:'prefabs',icon:'prefab'})),...Object.entries(assets.graphs).map(([id,g])=>({id,name:g.name,type:'graphs',icon:'graph'}))],query=$('#assetSearch').value.toLowerCase(),filtered=list.filter(a=>(this.filter==='all'||this.filter===a.type)&&a.name.toLowerCase().includes(query));$('#assetGrid').innerHTML=filtered.map(a=>`<div class="asset-card ${a.type}" data-asset="${esc(a.id)}" data-asset-type="${a.type}" draggable="true" title="${esc(a.name)}"><div class="asset-thumb ${a.type}">${a.type==='materials'?`<div class="asset-sphere" style="--swatch:${esc(a.color)}"></div>`:icon(a.icon)}</div><strong>${esc(a.name)}</strong><small>${{meshes:'Static Mesh',materials:'Material',prefabs:'Prefab',graphs:'Gameplay Graph'}[a.type]}</small></div>`).join('');$('#assetCount').textContent=`${filtered.length} assets`;}
  showBottom(tab){this.bottom=tab;for(const b of document.querySelectorAll('[data-bottom]'))b.classList.toggle('active',b.dataset.bottom===tab);for(const name of ['content','graph','log'])$('#'+name+'Panel').hidden=name!==tab;document.body.classList.remove('bottom-collapsed');if(tab==='graph'){document.body.classList.add('bottom-expanded');this.graphUI.render();}else document.body.classList.remove('bottom-expanded');}
  addActor(kind,position=null){if(this.runtime)return;const p=position?[...position]:[Math.round(this.camera.target[0]),1,Math.round(this.camera.target[2])];let added;
    this.commit('Add '+kind,()=>{let e;if(kind==='terrain'){const existing=this.scene.data.entities.find(e=>e.components.mesh?.asset==='terrain');if(existing){this.selection=existing.id;this.tool='terrain';return;}e=entity('Landscape','terrain',[0,0,0],[1,1,1],'sand');this.scene.data.assets.terrain??=createTerrain();e.locked=true;e.components.body={type:'static',shape:'box',mass:1};}else if(kind==='light'){e=entity('Point Light',null,p,[1,1,1]);e.components.light={type:'point',color:'#ffd4a3',intensity:8,range:12};}else if(kind==='player'){e=entity('Player','cylinder',vadd(p,[0,.5,0]),[.72,1.2,.72],'gold');e.components.controller={speed:6.5,jump:8.5};for(const other of this.scene.data.entities){delete other.components.player;delete other.components.controller;}e.components.player={};e.components.body={type:'dynamic',shape:'box',mass:1,friction:0,restitution:0,velocity:[0,0,0]};}else if(kind==='folder'){e=entity('New Group',null,[0,0,0],[1,1,1]);}else {const mesh=kind==='body'?'cube':kind;e=entity(kind==='body'?'Physics Body':this.meshList().find(m=>m.id===mesh)?.name.replace('SM_','')||'Mesh',mesh,p,[1,1,1],kind==='body'?'red':'stone');e.components.body={type:kind==='body'?'dynamic':'static',shape:mesh==='sphere'?'sphere':'box',mass:1,friction:.6,restitution:.1};}this.scene.add(e);this.selection=e.id;added=e;});if(kind==='terrain')this.setTool('terrain');return added;
  }
  useAsset(type,id,position){if(type==='meshes')this.addActor(id,position);if(type==='materials'){const e=this.scene.get(this.selection);if(!e?.components.mesh){this.toast('Select a mesh actor to apply a material');return;}this.commit('Apply material',()=>e.components.mesh.material=id);}if(type==='prefabs')this.instantiatePrefab(id,position);if(type==='graphs'){this.graphUI.graphId=id;this.showBottom('graph');}}
  deleteSelection(){const e=this.scene.get(this.selection);if(!e)return;if(e.locked){this.toast('Unlock this actor in Details before deleting');return;}this.commit('Delete actor',()=>{this.scene.remove(e.id);this.selection=null;});}
  duplicate(){const e=this.scene.get(this.selection);if(!e||e.components.mesh?.asset==='terrain')return;this.commit('Duplicate actor',()=>{const copy=this.scene.duplicate(e.id);this.selection=copy.id;if(copy.components.player){delete copy.components.player;delete copy.components.controller;}});}
  savePrefab(){const e=this.scene.get(this.selection);if(!e){this.toast('Select an actor or group first');return;}if(e.components.mesh?.asset==='terrain'){this.toast('Terrain is a project-level asset, not a prefab');return;}const name=prompt('Prefab asset name','PF_'+e.name.replace(/\s+/g,'_'));if(!name)return;this.commit('Create prefab',()=>{const entities=this.scene.subtree(e.id);entities[0].parent=null;translateEntity(entities[0],entities[0].transform.position.map(v=>-v));const id=uid('prefab');this.scene.data.assets.prefabs[id]={name,entities};e.components.prefab={asset:id};});this.filter='prefabs';this.renderAssets();this.toast('Prefab snapshot created. Double-click it to instantiate.');}
  instantiatePrefab(id,position){const prefab=this.scene.data.assets.prefabs[id];if(!prefab)return;this.commit('Instantiate prefab',()=>{const items=deepCopy(prefab.entities),map=new Map(items.map(e=>[e.id,uid()]));for(const e of items){e.id=map.get(e.id);e.parent=map.get(e.parent)||null;if(e.components.player){delete e.components.player;delete e.components.controller;}this.scene.add(e);}const root=items[0];const target=position||[this.camera.target[0],1.2,this.camera.target[2]];translateEntity(root,target.map((v,i)=>v-root.transform.position[i]));root.components.prefab={asset:id};this.selection=root.id;});}
  regenerateTerrain(){this.commit('Regenerate landscape',()=>{this.scene.data.assets.terrain=createTerrain((this.scene.data.assets.terrain.seed||1)+1);this.scene.data.assets.terrain.version=Date.now();});}
  play(){if(this.runtime){this.runtime.paused=!this.runtime.paused;this.updatePlayButtons();return;}try{this.previewScene=null;this.runtime=new GameRuntime(this.scene.serialize(),{onMessage:m=>{this.toast(m);$('#gameMessage').textContent=m;clearTimeout(this.gameMessageTimer);this.gameMessageTimer=setTimeout(()=>$('#gameMessage').textContent='',4000);},onScore:(s,t)=>$('#gameScore').textContent=`${s} / ${t}`,onError:m=>this.log('error',m)});$('#gameScore').textContent=`0 / ${this.runtime.targetScore}`;$('#gameMessage').textContent='';$('#playHud').hidden=false;document.body.classList.add('playing-editor');this.updatePlayButtons();this.inspector.render();$('#overlayCanvas').focus();this.log('info','Play in editor · isolated runtime scene · fixed Δt = 1/120 s');}catch(e){this.runtime=null;this.log('error','Could not enter Play: '+e.message);}}
  stop(){if(!this.runtime)return;const ticks=this.runtime.tick;this.runtime.input.clear();this.runtime=null;$('#playHud').hidden=true;document.body.classList.remove('playing-editor');this.updatePlayButtons();this.renderOutliner();this.inspector.render();this.log('info',`Stopped after ${ticks} fixed ticks; editor state unchanged`);}
  updatePlayButtons(){const playing=!!this.runtime;$('#playButton').classList.toggle('playing',playing);$('#playButton').lastElementChild.textContent=playing?(this.runtime.paused?'Resume':'Playing'):'Play';for(const id of ['pauseButton','stopButton','stepButton'])$('#'+id).disabled=!playing;$('#pauseButton').classList.toggle('active',!!this.runtime?.paused);}
  scrubAnimation(time){this.previewTime=time;const preview=new GameRuntime(this.scene.serialize());preview.time=time;preview.animate(0);preview.scene.invalidate();this.previewScene=preview;const label=this.inspector.root.querySelector('.timeline-time');if(label)label.textContent=time.toFixed(2)+' s';}
  focusSelection(){const e=this.activeScene.get(this.selection);if(!e){this.camera=new Camera();return;}let bounds=this.actorBounds(e,this.activeScene,this.runtime?.assets||this.assets);if(!bounds){const p=point(this.activeScene.world(e.id),[0,0,0]);bounds=[vsub(p,[1,1,1]),vadd(p,[1,1,1])];}const center=bounds[0].map((v,i)=>(v+bounds[1][i])*.5),size=vlength(vsub(bounds[1],bounds[0]));this.camera.focus(center,Math.max(1,size*.6));}
  actorBounds(e,scene,assets){const targets=scene.subtree(e.id).filter(e=>e.components.mesh);if(!targets.length)return null;const b=[[Infinity,Infinity,Infinity],[-Infinity,-Infinity,-Infinity]];for(const item of targets){const a=boundsTransform(assets.mesh(item.components.mesh.asset).bounds,scene.world(item.id));for(let k=0;k<3;k++){b[0][k]=Math.min(b[0][k],a[0][k]);b[1][k]=Math.max(b[1][k],a[1][k]);}}return b;}
  async importFiles(files){for(const file of files){try{if(file.size>50e6)throw Error('Import limit: 50 MB per file');const ext=file.name.split('.').pop().toLowerCase();if(ext==='json'){this.replace(JSON.parse(await file.text()),'Imported project');}else if(ext==='obj'){this.toast('Processing OBJ geometry in asset worker…');const mesh=await importOBJ(await file.text());mesh.name=file.name.replace(/\.obj$/i,'');const id=uid('mesh');this.commit('Import OBJ',()=>this.scene.data.assets.meshes[id]=mesh);this.addActor(id);this.focusSelection();this.log('info',`Imported ${file.name}: ${mesh.vertices.length/8} vertices, ${mesh.indices.length/3} triangles`);}else if(['png','jpg','jpeg','webp'].includes(ext)){const bitmap=await createImageBitmap(file),factor=Math.min(1,2048/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*factor));canvas.height=Math.max(1,Math.round(bitmap.height*factor));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const id=uid('material'),texture=canvas.toDataURL('image/png');this.commit('Import texture',()=>{this.scene.data.assets.materials[id]={name:'M_'+file.name.replace(/\.[^.]+$/,''),color:'#ffffff',roughness:.7,metallic:0,emission:0,texture};const e=this.scene.get(this.selection);if(e?.components.mesh)e.components.mesh.material=id;});this.filter='materials';this.renderAssets();}else throw Error('Supported imports: project JSON, OBJ, PNG, JPEG, WebP');this.toast('Imported '+file.name);}catch(e){this.log('error',`${file.name}: ${e.message}`);}}}
  async exportGame(){try{const runtime=document.querySelector('#vanta-runtime-source')?.textContent||await fetch('runtime.bundle.js').then(r=>{if(!r.ok)throw Error('Run npm run build to generate runtime.bundle.js');return r.text();}),css=document.querySelector('#vanta-inline-style')?.textContent||await fetch('styles.css').then(r=>r.text()),json=JSON.stringify(validateScene(this.scene.serialize())).replace(/</g,'\\u003c'),title=esc(this.scene.data.name);const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#1b2e32"><title>${title} — Vanta Forge</title><style>${css}</style></head><body class="game-only"><canvas id="game"></canvas><div class="standalone-ui"><div class="standalone-brand">VANTA FORGE / PLAYABLE WORLD</div><h1>${title.toUpperCase()}</h1><div class="objective"><small>RESTORE THE RELAY</small><strong>Collect the energy shards</strong><div><span id="score">0 / 0</span><span class="game-score-line"></span><span id="timer">0.0 s</span></div></div><div id="message"></div><div class="touch-pad"><button data-key="KeyW">▲</button><button data-key="KeyA">◀</button><button data-key="KeyS">▼</button><button data-key="KeyD">▶</button><button data-key="Space">JUMP</button></div><div class="standalone-bottom"><button class="export" id="restart">Restart</button><span id="status">Starting runtime…</span><span id="backend">WebGPU</span></div></div><script id="scene-data" type="application/json">${json}</script><script>${runtime.replace(/<\/script/gi,'<\\/script')}</script><script>VantaRuntime.launchStandalone(JSON.parse(document.getElementById('scene-data').textContent)).catch(e=>document.getElementById('status').textContent=e.message);</script></body></html>`;downloadFile(this.scene.data.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-game.html',html,'text/html');this.log('info',`Exported standalone game: ${(new Blob([html]).size/1024).toFixed(0)} KB; scene, assets, shaders, runtime embedded`);this.toast('Standalone web game exported');return html;}catch(e){this.log('error','Export failed: '+e.message);return null;}}
  menu(kind,anchor){const items={file:[['New empty world','new',''],['Open / import…','import','Ctrl O'],['Save locally','save','Ctrl S'],['Download project JSON','download-project',''],['Export standalone game','export-game',''],['Restore starter world','reset-demo','']],edit:[['Undo','undo','Ctrl Z'],['Redo','redo','Ctrl Shift Z'],['Duplicate actor','duplicate','Ctrl D'],['Delete actor','delete','Delete']],actor:[['Add cube','add:cube',''],['Add point light','add:light',''],['Add physics body','add:body',''],['Add player start','add:player',''],['Create group','new-folder',''],['Save as prefab','save-prefab',''],['Frame selected','frame','F']],add:[['Cube','add:cube',''],['Sphere','add:sphere',''],['Cylinder','add:cylinder',''],['Ring','add:torus',''],['Crystal','add:crystal',''],['Point light','add:light',''],['Physics body','add:body',''],['Player start','add:player',''],['Landscape','add:terrain','']],window:[['Content Browser','bottom:content',''],['Gameplay Graph','bottom:graph',''],['Output Log','bottom:log',''],['Details / Outliner','toggle-details',''],['Expand bottom panel','toggle-bottom',''],['Frame starter level','frame-all','']],camera:[['Perspective','camera:perspective',''],['Top','camera:top',''],['Front','camera:front',''],['Right','camera:right','']]};const popup=$('#menuPopup'),rect=anchor.getBoundingClientRect();popup.innerHTML=(items[kind]||[]).map(([label,action,key])=>`<button data-action="${action}">${label}<span>${key}</span></button>`).join('');popup.hidden=false;popup.style.left=Math.min(rect.left,innerWidth-230)+'px';popup.style.top=rect.bottom+4+'px';}
  async action(action){if(action?.startsWith('add:')){this.addActor(action.slice(4));return;}if(action?.startsWith('bottom:')){this.showBottom(action.slice(7));return;}if(action?.startsWith('camera:')){const kind=action.slice(7);if(kind==='perspective')this.camera=new Camera();else{this.camera.pitch=kind==='top'?Math.PI/2-.001:.05;this.camera.yaw=kind==='right'?Math.PI/2:0;this.camera.orbit();}$('#cameraMenu').innerHTML=icon('cube')+kind[0].toUpperCase()+kind.slice(1)+' <span class="chevron">⌄</span>';return;}
    switch(action){case 'save':await this.save();break;case 'undo':this.undo();break;case 'redo':this.redo();break;case 'duplicate':this.duplicate();break;case 'delete':this.deleteSelection();break;case 'frame':this.focusSelection();break;case 'frame-all':this.camera=new Camera();break;case 'play':this.play();break;case 'stop':this.stop();break;case 'pause':if(this.runtime){this.runtime.paused=!this.runtime.paused;this.updatePlayButtons();}break;case 'step':if(this.runtime){this.runtime.paused=true;this.runtime.step();this.runtime.follow(1);this.inspector.render();this.updatePlayButtons();}break;case 'snap':this.snap=!this.snap;$('#snapToggle').classList.toggle('active',this.snap);$('#snapText').textContent=this.snap?'0.5 ✓':'0.5';this.toast('Transform snapping '+(this.snap?'enabled':'disabled'));break;case 'colliders':this.colliders=!this.colliders;$('#collisionToggle').innerHTML=icon(this.colliders?'body':'sun')+(this.colliders?'Collision':'Lit');break;case 'world':this.select(null);if(innerWidth<=600)document.body.classList.add('mobile-details');break;case 'toggle-details':document.body.classList.toggle('mobile-details');break;case 'toggle-bottom':document.body.classList.toggle('bottom-expanded');break;case 'import':$('#fileInput').click();break;case 'download-project':downloadFile(this.scene.data.name.replace(/\W+/g,'-')+'.vanta.json',JSON.stringify(this.scene.serialize(),null,2));break;case 'export-game':await this.exportGame();break;case 'new-folder':this.addActor('folder');break;case 'save-prefab':this.savePrefab();break;case 'add-node':this.graphUI.addNode();break;case 'compile-graph':{const errors=this.graphUI.status();this.toast(errors.length?errors.join('; '):'Graph compiled successfully · typed, acyclic, bounded',!!errors.length);this.log(errors.length?'warn':'info',errors.length?errors.join('; '):'Compiled '+this.graphUI.graph.name);break;}case 'new-graph':{const name=prompt('Gameplay graph name','BP_NewBehavior');if(!name)return;this.commit('Create gameplay graph',()=>{const id=uid('graph');this.scene.data.assets.graphs[id]={id,name,nodes:[graphNode('Start','start')],edges:[]};this.graphUI.graphId=id;});this.showBottom('graph');break;}case 'clear-log':this.logs=[];this.renderLog();$('#logBadge').textContent='';break;case 'help':$('#helpDialog').showModal();break;case 'close-help':$('#helpDialog').close();break;case 'new':if(confirm('Create a new world? Download your current project first to keep another copy.')){const data=createDemo();data.name='Untitled World';data.entities=data.entities.filter(e=>e.components.mesh?.asset==='terrain'||e.components.light?.type==='directional');this.replace(data,'New world');}break;case 'reset-demo':if(confirm('Restore the Aether Relay starter world?'))this.replace(createDemo(),'Restored starter world');break;}}
  bindUI(){document.addEventListener('click',e=>{const button=e.target.closest('button');if(button?.dataset.menu){this.menu(button.dataset.menu,button);return;}if(!e.target.closest('#menuPopup'))$('#menuPopup').hidden=true;if(button?.dataset.action){$('#menuPopup').hidden=true;Promise.resolve(this.action(button.dataset.action)).catch(err=>this.log('error',err.message));}if(button?.dataset.tool)this.setTool(button.dataset.tool);if(button?.dataset.bottom)this.showBottom(button.dataset.bottom);if(button?.dataset.filter){this.filter=button.dataset.filter;for(const b of document.querySelectorAll('[data-filter]'))b.classList.toggle('active',b===button);this.renderAssets();}});
    $('#placeSearch').oninput=()=>this.renderPlace();$('#outlinerSearch').oninput=()=>this.renderOutliner();$('#assetSearch').oninput=()=>this.renderAssets();$('#fileInput').onchange=e=>{this.importFiles([...e.target.files]);e.target.value='';};
    $('#outlinerTree').onclick=e=>{const visibility=e.target.closest('[data-visibility]');if(visibility){this.commit('Toggle visibility',()=>{const actor=this.scene.get(visibility.dataset.visibility);actor.visible=actor.visible===false;});return;}const fold=e.target.closest('[data-fold]');if(fold){const id=fold.dataset.fold;this.folded.has(id)?this.folded.delete(id):this.folded.add(id);this.renderOutliner();return;}const row=e.target.closest('[data-entity]');if(row)this.select(row.dataset.entity);};$('#outlinerTree').ondblclick=e=>{if(e.target.closest('[data-entity]'))this.focusSelection();};
    for(const list of [$('#placeActors'),$('#placeSystems')]){list.ondblclick=e=>{const item=e.target.closest('[data-place]');if(item)this.addActor(item.dataset.place);};list.ondragstart=e=>{const item=e.target.closest('[data-place]');if(item)e.dataTransfer.setData('application/x-vanta',JSON.stringify({place:item.dataset.place}));};}
    $('#assetGrid').ondblclick=e=>{const asset=e.target.closest('[data-asset]');if(asset)this.useAsset(asset.dataset.assetType,asset.dataset.asset);};$('#assetGrid').ondragstart=e=>{const asset=e.target.closest('[data-asset]');if(asset)e.dataTransfer.setData('application/x-vanta',JSON.stringify({type:asset.dataset.assetType,id:asset.dataset.asset}));};
    const viewport=$('#viewport');viewport.ondragover=e=>{e.preventDefault();};viewport.ondrop=e=>{e.preventDefault();if(e.dataTransfer.files.length){this.importFiles([...e.dataTransfer.files]);return;}try{const data=JSON.parse(e.dataTransfer.getData('application/x-vanta')),rect=$('#overlayCanvas').getBoundingClientRect(),hit=this.pick(e.clientX-rect.left,e.clientY-rect.top),ray=this.ray(e.clientX-rect.left,e.clientY-rect.top),p=hit?.position||(ray&&Math.abs(ray.dir[1])>.001?vadd(ray.origin,vmul(ray.dir,-ray.origin[1]/ray.dir[1])):[0,0,0]);p[1]+=.6;if(data.place)this.addActor(data.place,p);else this.useAsset(data.type,data.id,p);}catch(error){this.log('warn',error.message);}};
    addEventListener('keydown',e=>this.keydown(e));addEventListener('keyup',e=>{this.input.up(e.code);this.runtime?.input.up(e.code);});addEventListener('blur',()=>{this.input.clear();this.runtime?.input.clear();});addEventListener('beforeunload',e=>{if(this.dirty){e.preventDefault();e.returnValue='';}});
    for(const b of document.querySelectorAll('[data-game-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);this.runtime?.input.down(b.dataset.gameKey);};b.onpointerup=()=>this.runtime?.input.up(b.dataset.gameKey);b.onpointercancel=()=>this.runtime?.input.up(b.dataset.gameKey);}
  }
  keydown(e){const typing=/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)||e.target.isContentEditable;if(e.code==='Escape'){this.stop();$('#menuPopup').hidden=true;document.body.classList.remove('mobile-details');return;}if(typing)return;const mod=e.ctrlKey||e.metaKey;if(mod){const actions={KeyS:'save',KeyZ:e.shiftKey?'redo':'undo',KeyY:'redo',KeyD:'duplicate',KeyO:'import'};if(actions[e.code]){e.preventDefault();this.action(actions[e.code]);return;}}if(e.altKey&&e.code==='KeyP'){e.preventDefault();this.play();return;}if(this.runtime){if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();this.runtime.input.down(e.code);if(e.code==='KeyR')this.runtime.respawn();return;}this.input.down(e.code);if(this.drag?.type==='orbit')return;const shortcuts={KeyW:()=>this.setTool('move'),KeyE:()=>this.setTool('rotate'),KeyR:()=>this.setTool('scale'),KeyF:()=>this.focusSelection(),Delete:()=>this.deleteSelection(),Backspace:()=>this.deleteSelection()};if(shortcuts[e.code]){e.preventDefault();shortcuts[e.code]();}}
  ray(x,y){const rect=$('#overlayCanvas').getBoundingClientRect();return this.renderer.vp?cameraRay(x,y,rect.width,rect.height,this.renderer.vp):null;}
  pick(x,y,onlyTerrain=false){const ray=this.ray(x,y);if(!ray)return null;const scene=this.activeScene,assets=this.runtime?.assets||this.previewScene?.assets||this.assets;let best=null;for(const e of scene.data.entities){if(e.visible===false||(onlyTerrain&&e.components.mesh?.asset!=='terrain'))continue;let ancestor=scene.get(e.parent),hidden=false;while(ancestor){if(ancestor.visible===false)hidden=true;ancestor=scene.get(ancestor.parent);}if(hidden)continue;const m=scene.world(e.id);if(e.components.mesh){const mesh=assets.mesh(e.components.mesh.asset),b=boundsTransform(mesh.bounds,m),coarse=rayBox(ray.origin,ray.dir,b);if(coarse===null||best&&coarse>best.distance)continue;const inv=inverse(m);if(!inv)continue;const localOrigin=point(inv,ray.origin),localDir=direction(inv,ray.dir),hit=intersectMesh(mesh,localOrigin,localDir);if(hit!==null&&(!best||hit<best.distance))best={entity:e,distance:hit,position:vadd(ray.origin,vmul(ray.dir,hit))};}else if(e.components.light&&!onlyTerrain){const p=point(m,[0,0,0]),b=[vsub(p,[.4,.4,.4]),vadd(p,[.4,.4,.4])],hit=rayBox(ray.origin,ray.dir,b);if(hit!==null&&(!best||hit<best.distance))best={entity:e,distance:hit,position:vadd(ray.origin,vmul(ray.dir,hit))};}}return best;}
  bindViewport(){const overlay=$('#overlayCanvas');overlay.oncontextmenu=e=>e.preventDefault();overlay.addEventListener('wheel',e=>{e.preventDefault();if(this.runtime)return;this.camera.distance=clamp(this.camera.distance*Math.exp(e.deltaY*.001),.8,180);this.camera.orbit();},{passive:false});
    overlay.onpointerdown=e=>{e.preventDefault();overlay.focus();if(this.runtime)return;overlay.setPointerCapture(e.pointerId);const rect=overlay.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;let type=e.button===2||e.altKey?'orbit':e.button===1?'pan':'select',handle=null;
      if(type==='select'&&this.tool==='terrain'){const hit=this.pick(x,y,true);if(hit){type='terrain';this.brushPoint=hit.position;}}
      if(type==='select'){handle=this.gizmoHandles.filter(h=>h.distance(x,y)<10).sort((a,b)=>a.distance(x,y)-b.distance(x,y))[0];if(handle&&!this.scene.get(this.selection)?.locked)type='gizmo';}
      this.drag={type,x,y,lastX:x,lastY:y,clientX:e.clientX,clientY:e.clientY,handle,before:['gizmo','terrain'].includes(type)?this.scene.serialize():null,transform:this.selection?deepCopy(this.scene.get(this.selection)?.transform):null,world:this.selection?this.scene.world(this.selection):null};if(type==='terrain')this.sculptAt(x,y,e.shiftKey);};
    overlay.onpointermove=e=>{const rect=overlay.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;this.mouse=[x,y];if(!this.drag){if(this.tool==='terrain'){const hit=this.pick(x,y,true);this.brushPoint=hit?.position;}else overlay.style.cursor=this.gizmoHandles.some(h=>h.distance(x,y)<10)?'grab':'default';return;}const drag=this.drag,dx=x-drag.lastX,dy=y-drag.lastY;drag.lastX=x;drag.lastY=y;if(drag.type==='orbit'){this.camera.yaw-=dx*.007;this.camera.pitch=clamp(this.camera.pitch+dy*.007,-1.4,1.54);this.camera.orbit();}else if(drag.type==='pan'){const front=vnorm(vsub(this.camera.target,this.camera.eye)),right=vnorm(vcross(front,[0,1,0])),up=vnorm(vcross(right,front)),scale=this.camera.distance*.0015;this.camera.target=vadd(this.camera.target,vadd(vmul(right,-dx*scale),vmul(up,dy*scale)));this.camera.orbit();}else if(drag.type==='terrain')this.sculptAt(x,y,e.shiftKey);else if(drag.type==='gizmo')this.dragGizmo(x,y);};
    const end=e=>{if(!this.drag)return;const drag=this.drag;this.drag=null;if(drag.type==='select'&&Math.hypot(e.clientX-drag.clientX,e.clientY-drag.clientY)<6){const rect=overlay.getBoundingClientRect(),hit=this.pick(e.clientX-rect.left,e.clientY-rect.top);this.select(hit?.entity.id||null);}if(drag.before)this.finishEdit(drag.before,drag.type==='terrain'?'Sculpt terrain':'Transform actor');};overlay.onpointerup=end;overlay.onpointercancel=end;overlay.ondblclick=()=>this.focusSelection();}
  sculptAt(x,y,lower){const hit=this.pick(x,y,true);if(!hit)return;this.brushPoint=hit.position;sculptTerrain(this.scene.data.assets.terrain,hit.position[0],hit.position[2],this.brushRadius,this.brushStrength*(lower?-1:1));this.scene.invalidate();}
  dragGizmo(x,y){const drag=this.drag,e=this.scene.get(this.selection),h=drag.handle;if(!e)return;const delta=[x-drag.x,y-drag.y],axis=h.axis,axisVec=[0,0,0];axisVec[axis]=1;let amount=(delta[0]*h.dx+delta[1]*h.dy)/(h.dx*h.dx+h.dy*h.dy)*h.length;
    if(this.tool==='move'){if(this.snap)amount=Math.round(amount/.5)*.5;const worldDelta=vmul(axisVec,amount),parent=e.parent?inverse(this.scene.world(e.parent)):null,localDelta=parent?direction(parent,worldDelta):worldDelta;e.transform.position=vadd(drag.transform.position,localDelta);}
    if(this.tool==='scale'){amount=1+amount/Math.max(h.length,1);if(this.snap)amount=Math.round(amount*10)/10;e.transform.scale=[...drag.transform.scale];e.transform.scale[axis]=Math.max(.01,drag.transform.scale[axis]*amount);}
    if(this.tool==='rotate'){const center=h.center,a=Math.atan2(drag.y-center[1],drag.x-center[0]),b=Math.atan2(y-center[1],x-center[0]);let angle=deg(b-a)*h.sign;if(this.snap)angle=Math.round(angle/15)*15;const rotation=[0,0,0];rotation[axis]=angle;const r=compose({position:[0,0,0],rotation,scale:[1,1,1]}),world=new Float32Array(drag.world);world[12]=world[13]=world[14]=0;let result=mmul(r,world);result[12]=drag.world[12];result[13]=drag.world[13];result[14]=drag.world[14];if(e.parent)result=mmul(inverse(this.scene.world(e.parent)),result);e.transform=decomposeTransform(result);}
    this.scene.invalidate();}
  drawOverlay(){const overlay=$('#overlayCanvas'),rect=overlay.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2),w=rect.width,h=rect.height;if(overlay.width!==Math.round(w*ratio)||overlay.height!==Math.round(h*ratio)){overlay.width=Math.round(w*ratio);overlay.height=Math.round(h*ratio);}const ctx=overlay.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);this.gizmoHandles=[];const vp=this.renderer.vp;if(!vp)return;const scene=this.activeScene,assets=this.runtime?.assets||this.previewScene?.assets||this.assets,project=p=>screenPoint(p,vp,w,h);
    const drawBox=(bounds,matrix,color,dashed=false)=>{const corners=[];for(let i=0;i<8;i++)corners.push(project(point(matrix,[bounds[i&1?1:0][0],bounds[i&2?1:0][1],bounds[i&4?1:0][2]])));ctx.strokeStyle=color;ctx.lineWidth=1;ctx.setLineDash(dashed?[4,3]:[]);ctx.beginPath();for(let i=0;i<8;i++)for(const bit of [1,2,4])if(!(i&bit)){const a=corners[i],b=corners[i|bit];if(a[2]>0&&b[2]>0&&a[2]<1&&b[2]<1){ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);}}ctx.stroke();ctx.setLineDash([]);};
    if(this.colliders){for(const e of scene.data.entities){if(!e.components.body||e.components.mesh?.asset==='terrain'||e.visible===false)continue;const bounds=assets.mesh(e.components.mesh?.asset||'cube').bounds;drawBox(bounds,scene.world(e.id),e.components.body.trigger?'#e8c77688':'#86d99877');}}
    if(this.runtime)return;
    for(const e of scene.data.entities.filter(e=>e.components.light?.type==='point'&&e.visible!==false)){const p=project(point(scene.world(e.id),[0,0,0]));if(p[2]<=0||p[2]>=1)continue;ctx.strokeStyle=e.id===this.selection?'#91f2c8':'#e6d8a397';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p[0],p[1],5,0,Math.PI*2);for(let i=0;i<8;i++){const a=i/8*Math.PI*2;ctx.moveTo(p[0]+Math.cos(a)*8,p[1]+Math.sin(a)*8);ctx.lineTo(p[0]+Math.cos(a)*11,p[1]+Math.sin(a)*11);}ctx.stroke();}
    if(this.tool==='terrain'&&this.brushPoint){ctx.beginPath();ctx.strokeStyle='#a8f3cc';ctx.lineWidth=1.5;for(let i=0;i<=64;i++){const a=i/64*Math.PI*2,p=project(vadd(this.brushPoint,[Math.cos(a)*this.brushRadius,.12,Math.sin(a)*this.brushRadius]));i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]);}ctx.stroke();return;}
    const e=scene.get(this.selection);if(!e)return;const matrix=scene.world(e.id);if(e.components.mesh&&e.components.mesh.asset!=='terrain')drawBox(assets.mesh(e.components.mesh.asset).bounds,matrix,'#9ef3d582',true);
    if(e.locked)return;const origin=point(matrix,[0,0,0]),center=project(origin);if(center[2]<=0||center[2]>=1)return;const length=vlength(vsub(this.camera.eye,origin))*.115,colors=['#ee9387','#a2d899','#84b9ef'],lineDistance=(x,y,a,b)=>{const dx=b[0]-a[0],dy=b[1]-a[1],t=clamp(((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy||1),0,1);return Math.hypot(x-a[0]-dx*t,y-a[1]-dy*t);};
    for(let axis=0;axis<3;axis++){const local=[0,0,0];local[axis]=length;const vector=this.tool==='scale'?vmul(vnorm(direction(matrix,local)),length):local,end=project(vadd(origin,vector)),dx=end[0]-center[0],dy=end[1]-center[1];ctx.strokeStyle=colors[axis];ctx.fillStyle=colors[axis];ctx.lineWidth=2.2;ctx.shadowColor='#0008';ctx.shadowBlur=3;
      if(this.tool==='rotate'){const ring=[];for(let i=0;i<=64;i++){const a=i/64*Math.PI*2,p=[0,0,0];p[(axis+1)%3]=Math.cos(a)*length*.65;p[(axis+2)%3]=Math.sin(a)*length*.65;ring.push(project(vadd(origin,p)));}ctx.beginPath();ring.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.stroke();const normal=[0,0,0];normal[axis]=1;this.gizmoHandles.push({axis,center,length,dx,dy,sign:vdot(normal,vsub(this.camera.eye,origin))>0?-1:1,distance:(x,y)=>Math.min(...ring.slice(1).map((p,i)=>lineDistance(x,y,ring[i],p)))});
      }else{ctx.beginPath();ctx.moveTo(center[0],center[1]);ctx.lineTo(end[0],end[1]);ctx.stroke();if(this.tool==='scale'){ctx.fillRect(end[0]-4,end[1]-4,8,8);}else{const a=Math.atan2(dy,dx);ctx.beginPath();ctx.moveTo(end[0],end[1]);ctx.lineTo(end[0]-Math.cos(a-.42)*11,end[1]-Math.sin(a-.42)*11);ctx.lineTo(end[0]-Math.cos(a+.42)*11,end[1]-Math.sin(a+.42)*11);ctx.closePath();ctx.fill();}ctx.font='bold 10px sans-serif';ctx.fillText('XYZ'[axis],end[0]+7,end[1]-6);this.gizmoHandles.push({axis,center,length,dx,dy,distance:(x,y)=>lineDistance(x,y,[center[0]+dx*.16,center[1]+dy*.16],end)});}
    }ctx.shadowBlur=0;ctx.fillStyle='#f2f5eb';ctx.fillRect(center[0]-3,center[1]-3,6,6);
  }
  frame(now){if(!this.running)return;const dt=Math.min(.1,(now-this.lastFrame)/1000);this.lastFrame=now;try{if(this.runtime){this.runtime.update(dt);this.renderer.render(this.runtime.scene,this.runtime.assets,this.runtime.camera);$('#gameTime').textContent=this.runtime.time.toFixed(1)+' s';}else {if(this.drag?.type==='orbit'){const front=vnorm(vsub(this.camera.target,this.camera.eye)),right=vnorm(vcross(front,[0,1,0])),keys=this.input.keys,speed=(keys.has('ShiftLeft')?18:7)*dt,move=vadd(vmul(front,+(keys.has('KeyW'))-+(keys.has('KeyS'))),vmul(right,+(keys.has('KeyD'))-+(keys.has('KeyA'))));this.camera.target=vadd(this.camera.target,vmul(move,speed));this.camera.orbit();}this.renderer.render(this.previewScene?.scene||this.scene,this.previewScene?.assets||this.assets,this.camera,this.selection);}this.drawOverlay();}catch(e){this.log('error','Frame error: '+e.message);this.running=false;return;}this.frameCount++;if(now-this.statsTime>700){const fps=this.frameCount*1000/(now-this.statsTime),s=this.renderer.stats;$('#renderStats').textContent=`${Math.round(fps)} FPS  ·  ${s.draws} draws  ·  ${(s.triangles/1000).toFixed(1)}k tris  ·  ${s.visible}/${s.total} visible`;this.statsTime=now;this.frameCount=0;if(this.runtime){for(const node of document.querySelectorAll('.graph-node'))node.classList.toggle('active-node',this.runtime.lastNodes.has(node.dataset.node));if(this.runtime.paused)this.inspector.render();}}requestAnimationFrame(t=>this.frame(t));}
}
const editor=new ForgeEditor();window.vanta=editor;editor.start().catch(error=>{console.error(error);editor.log('error',error.message);});
