import {NODE_TYPES,graphNode,validateGraph} from './graph.js';
import {uid} from './scene.js';
import {point,deepCopy} from './math.js';
export const $=s=>document.querySelector(s);
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ICON_PATHS={
  cube:'M12 3 3 8v9l9 5 9-5V8L12 3Zm0 10v9M3 8l9 5 9-5M8 5l9 5',sphere:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM3 12h18M12 3c-5 5-5 13 0 18 5-5 5-13 0-18Z',cylinder:'M4 6v12c0 5 16 5 16 0V6M4 6c0-5 16-5 16 0S4 11 4 6Z',torus:'M21 12a9 7 0 1 1-18 0 9 7 0 0 1 18 0ZM17 12a5 3 0 1 1-10 0 5 3 0 0 1 10 0Z',crystal:'m12 2 7 8-7 12-7-12 7-8Zm0 0v20M5 10h14',terrain:'m2 19 6-12 4 6 4-9 6 15H2Zm4-8 2 2 2-2M14 8l2 2 2-2',sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5',light:'M9 18h6m-6 3h6M8 15c-6-8 2-15 7-10 4 3 2 7 0 10v2H9v-2',player:'M15 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM7 22l1-9-3 4M17 22l-1-9 3 4M8 13c0-5 8-5 8 0M8 18h8',save:'M4 3h13l4 4v14H3V3h1Zm3 0v7h10V3M7 21v-7h10v7',import:'M12 3v12m-4-4 4 4 4-4M3 15v6h18v-6',export:'M12 16V3m-4 4 4-4 4 4M3 13v8h18v-8',move:'M12 2v20M2 12h20M8 6l4-4 4 4M8 18l4 4 4-4M6 8l-4 4 4 4M18 8l4 4-4 4',rotate:'M20 9a8 8 0 1 0 0 7M20 3v6h-6',scale:'M14 3h7v7M21 3l-9 9M3 9h12v12H3Z',grid:'M3 3h18v18H3ZM3 9h18M3 15h18M9 3v18M15 3v18',play:'m7 3 14 9-14 9V3Z',pause:'M8 4v16M16 4v16',stop:'M5 5h14v14H5Z',step:'m4 4 12 8-12 8V4ZM20 4v16',search:'M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0ZM15 15l6 6',folder:'M3 6h7l2 3h9v12H3V6Z', 'folder-plus':'M3 6h7l2 3h9v12H3V6ZM12 12v6m-3-3h6',graph:'M3 3h6v6H3ZM15 15h6v6h-6ZM3 15h6v6H3ZM9 6h6v12M9 18h6',prefab:'m12 2 10 5v10l-10 5L2 17V7l10-5ZM12 8l4 2v5l-4 2-4-2v-5l4-2ZM2 7l6 3m8 0 6-3M12 17v5',layers:'m12 3 10 6-10 6L2 9l10-6ZM2 13l10 6 10-6M2 17l10 6 10-6',shapes:'M3 3h8v8H3ZM16 3l6 9H12l4-9ZM11 18a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM15 15h7v7h-7Z',settings:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8ZM9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3Z',sliders:'M3 6h18M3 12h18M3 18h18M7 3v6M17 9v6M10 15v6',terminal:'m4 6 6 6-6 6M12 18h8',frame:'M9 3H3v6m12-6h6v6M3 15v6h6m12-6v6h-6',expand:'m4 8 8-5 8 5M4 16l8 5 8-5',cursor:'M5 2v19l5-6 4 7 4-2-4-7h8L5 2Z',body:'M4 4h16v16H4ZM4 4l16 16M20 4 4 20',animation:'M3 4h18v16H3ZM3 8h18M3 16h18M7 4v4m5-4v4m5-4v4M7 16v4m5-4v4m5-4v4m-6-9 5 3-5 3v-6Z',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12ZM15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',link:'m9 8 3-3c6-6 12 0 6 6l-3 3M9 10l-3 3c-6 6 0 12 6 6l3-3m-7-1 8-8'
};
export const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${ICON_PATHS[name]||ICON_PATHS.cube}"/></svg>`;
export function applyIcons(root=document){for(const el of root.querySelectorAll('[data-icon]'))el.innerHTML=icon(el.dataset.icon);}
export const entityIcon=e=>e.components.player?'player':e.components.light?(e.components.light.type==='directional'?'sun':'light'):e.components.graph?'graph':e.components.mesh?(e.components.mesh.asset in ICON_PATHS?e.components.mesh.asset:'cube'):'folder';
export function setPath(object,path,value){const parts=path.split('.');let o=object;for(const p of parts.slice(0,-1)){if(p==='__proto__'||p==='constructor'||p==='prototype')throw Error('Unsafe property path');o=o[p];if(o==null)throw Error('Missing property path');}o[parts.at(-1)]=value;}
export class InspectorUI {
  constructor(editor){this.editor=editor;this.root=$('#inspector');this.root.addEventListener('change',e=>this.change(e));this.root.addEventListener('click',e=>this.click(e));this.root.addEventListener('input',e=>{if(e.target.id==='animationScrub')editor.scrubAnimation(Number(e.target.value));if(e.target.id==='brushRadius')editor.brushRadius=Number(e.target.value);if(e.target.id==='brushStrength')editor.brushStrength=Number(e.target.value);});}
  input(path,value,type='number',attributes=''){return `<input data-prop="${esc(path)}" type="${type}" ${type==='checkbox'?value?'checked':'':`value="${esc(value)}"`} ${attributes}>`;}
  select(path,value,options){return `<select data-prop="${esc(path)}">${options.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select>`;}
  row(label,field){return `<div class="property-row"><label>${esc(label)}</label><div>${field}</div></div>`;}
  section(title,content,kind='settings',removable=null){return `<section class="component"><div class="component-title"><span>▾</span>${icon(kind)} ${esc(title)}${removable?`<button data-remove-component="${esc(removable)}" title="Remove component">×</button>`:''}</div><div class="component-fields">${content}</div></section>`;}
  render(){
    const ed=this.editor,scene=ed.runtime?.scene||ed.scene,e=scene.get(ed.selection),data=scene.data,assets=data.assets;
    if(!e){this.root.innerHTML=`<div class="inspector-empty"><h3>Your world starts here.</h3><p>Select an actor to edit its components, or tune the environment below.</p></div>`+this.section('World environment',this.row('Exposure',this.input('!settings.exposure',data.settings.exposure,'number','min="0.1" max="5" step="0.05"'))+this.row('Ambient',this.input('!settings.ambient',data.settings.ambient,'number','min="0" max="3" step="0.05"'))+this.row('Fog density',this.input('!settings.fog',data.settings.fog,'number','min="0" max="0.1" step="0.001"')),'sun');return;}
    const input=this.input.bind(this),select=this.select.bind(this),row=this.row.bind(this),section=this.section.bind(this),c=e.components;
    let html=`<div class="inspector-heading">${icon(entityIcon(e))}<div>${input('name',e.name,'text')}<small>${ed.runtime?'Runtime instance · read only':c.prefab?'Prefab instance':'Actor instance'} &nbsp;·&nbsp; ${Object.keys(c).length} components</small></div></div>`;
    const vector=(label,path,values)=>`<div class="vector-row"><span class="vector-label">${label}</span>${values.map((v,i)=>`<div class="axis-input"><span class="${'xyz'[i]}">${'XYZ'[i]}</span>${input(`${path}.${i}`,Number(v.toFixed(3)),'number',`step="${path.includes('rotation')?1:.1}" ${e.locked?'disabled':''}`)}</div>`).join('')}</div>`;
    html+=section('Transform',vector('Location','transform.position',e.transform.position)+vector('Rotation','transform.rotation',e.transform.rotation)+vector('Scale','transform.scale',e.transform.scale)+row('Parent',select('parent',e.parent||'',[['','World (root)'],...data.entities.filter(x=>x.id!==e.id&&!x.components.body).map(x=>[x.id,x.name])]))+row('Editor',`<label class="checkbox-label">${input('visible',e.visible!==false,'checkbox')} Visible &nbsp;${input('locked',e.locked,'checkbox')} Locked</label>`),'move');
    if(c.mesh){html+=section('Static Mesh',row('Mesh',select('components.mesh.asset',c.mesh.asset,ed.meshList().map(m=>[m.id,m.name])))+row('Material',select('components.mesh.material',c.mesh.material,Object.entries(assets.materials).map(([id,m])=>[id,m.name])))+row('Shadows',`<label class="checkbox-label">${input('components.mesh.castShadow',c.mesh.castShadow!==false,'checkbox')} Cast shadows</label>`),'cube','mesh');const m=assets.materials[c.mesh.material];if(m)html+=section('Material · '+m.name,row('Base color',`<div class="property-inline"><div class="material-swatch" style="background:${esc(m.color)}"></div>${input('@color',m.color,'color')}</div>`)+row('Roughness',input('@roughness',m.roughness,'range','min="0.045" max="1" step="0.01"'))+row('Metallic',input('@metallic',m.metallic,'range','min="0" max="1" step="0.01"'))+row('Emission',input('@emission',m.emission,'number','min="0" max="20" step="0.1"'))+`<p class="field-note">Shared material · affects every actor using this asset.${m.texture?' Embedded base-color texture.':''}</p>`,'sphere');}
    if(c.body){const b=c.body;html+=section('Rigid Body',row('Motion type',select('components.body.type',b.type,[['static','Static'],['dynamic','Dynamic']]))+row('Collider',select('components.body.shape',b.shape,[['box','AABB box'],['sphere','Sphere']]))+row('Mass · kg',input('components.body.mass',b.mass,'number','min="0.01" max="10000" step="0.1"'))+row('Friction',input('components.body.friction',b.friction??.6,'number','min="0" max="2" step="0.05"'))+row('Restitution',input('components.body.restitution',b.restitution??.05,'number','min="0" max="1" step="0.05"'))+row('Trigger',`<label class="checkbox-label">${input('components.body.trigger',b.trigger,'checkbox')} Overlap events only</label>`)+(b.shape==='sphere'?row('Radius',input('components.body.radius',b.radius??.5,'number','min="0.01" step="0.05"')):'')+(ed.runtime?`<p class="field-note">Velocity: ${(b.velocity||[0,0,0]).map(v=>v.toFixed(2)).join(', ')} m/s</p>`:''),'body','body');}
    if(c.controller){html+=section('Character Controller',row('Speed · m/s',input('components.controller.speed',c.controller.speed,'number','min="0" max="50" step="0.5"'))+row('Jump · m/s',input('components.controller.jump',c.controller.jump,'number','min="0" max="30" step="0.5"'))+`<p class="field-note">Camera-relative movement, grounded jumping, gravity and collision resolution.</p>`,'player','controller');}
    if(c.light){const l=c.light;html+=section(l.type==='directional'?'Directional Light':'Point Light',row('Color',input('components.light.color',l.color,'color'))+row('Intensity',input('components.light.intensity',l.intensity,'number','min="0" max="100" step="0.2"'))+(l.type==='point'?row('Range · m',input('components.light.range',l.range,'number','min="0.1" max="100" step="0.5"')):vector('Direction','components.light.direction',l.direction||[-.5,.85,.3])),'light','light');}
    if(c.graph){html+=section('Gameplay Graph',row('Asset',select('components.graph.asset',c.graph.asset,Object.entries(assets.graphs).map(([id,g])=>[id,g.name])))+`<button class="quiet" data-inspect-action="open-graph">${icon('graph')} Open gameplay graph →</button><p class="field-note">Typed data + execution wires. Runs in the fixed-update runtime, never as eval.</p>`,'graph','graph');}
    if(c.animation){const a=c.animation,track=a.tracks?.[ed.animationTrack||0];html+=section('Animation',row('Duration · s',input('components.animation.duration',a.duration,'number','min="0.01" max="1000" step="0.1"'))+row('Loop',input('components.animation.loop',a.loop,'checkbox'))+row('Track',`<select id="animationTrack">${(a.tracks||[]).map((t,i)=>`<option value="${i}" ${i===(ed.animationTrack||0)?'selected':''}>${esc(t.property)}</option>`).join('')}</select>`)+(track?track.keys.map((k,i)=>`<div class="animation-keys">${input(`components.animation.tracks.${ed.animationTrack||0}.keys.${i}.time`,k.time,'number','min="0" step="0.1"')}${input(`components.animation.tracks.${ed.animationTrack||0}.keys.${i}.value`,k.value,'number','step="0.1"')}<button data-delete-key="${i}">×</button></div>`).join(''):'')+`<div class="property-inline"><button class="quiet" data-inspect-action="add-key">＋ Keyframe</button><button class="quiet" data-inspect-action="add-track">＋ Track</button></div><input id="animationScrub" type="range" min="0" max="${a.duration}" step="0.01" value="${ed.previewTime??0}"><div class="property-inline"><span class="timeline-time">${(ed.previewTime??0).toFixed(2)} s</span><button class="quiet" data-inspect-action="clear-preview">Reset preview</button></div>`,'animation','animation');}
    if(c.mesh?.asset==='terrain'){html+=section('Landscape Sculpt',`<p class="field-note">Select the terrain tool, then drag on the landscape. Hold Shift to lower. One stroke = one undo entry.</p>`+row('Radius · m','<input id="brushRadius" type="range" min="1" max="15" step="0.5" value="'+ed.brushRadius+'">')+row('Strength','<input id="brushStrength" type="range" min="0.05" max="1" step="0.05" value="'+ed.brushStrength+'">')+`<button class="quiet" data-inspect-action="terrain-tool">${icon('terrain')} Activate sculpt tool</button><button class="quiet" data-inspect-action="regenerate-terrain">Regenerate landscape</button>`,'terrain');}
    html+=`<div class="component-actions"><select id="addComponentType"><option value="body">Rigid Body</option><option value="graph">Gameplay Graph</option><option value="animation">Animation</option><option value="controller">Player Controller</option><option value="light">Point Light</option></select><button data-inspect-action="add-component">＋ Add</button></div><div class="inspector-footer">ENTITY ${esc(e.id)}<br>WORLD UNITS: METERS · ROTATION: DEGREES</div>`;
    this.root.innerHTML=html;if(ed.runtime)for(const node of this.root.querySelectorAll('input,select,button'))node.disabled=true;
  }
  change(event){const ed=this.editor,target=event.target;if(target.id==='animationTrack'){ed.animationTrack=Number(target.value);this.render();return;}const path=target.dataset.prop;if(!path)return;const e=ed.scene.get(ed.selection);let value=target.type==='checkbox'?target.checked:target.type==='number'||target.type==='range'?Number(target.value):target.value;
    ed.commit('Edit '+path,()=>{if(typeof value==='number'&&!Number.isFinite(value))throw Error('Value must be finite');if(path.startsWith('transform.scale')&&value<.01)throw Error('Scale must be positive');if(path==='parent'){if(value===e.id)throw Error('An actor cannot parent itself');let parent=ed.scene.get(value);while(parent){if(parent.id===e.id)throw Error('Cyclic hierarchy');parent=ed.scene.get(parent.parent);}if(value&&e.components.body?.type==='dynamic')throw Error('Dynamic bodies must remain at the world root');value||=null;}if(path==='components.body.type'&&value==='dynamic'&&(e.parent||e.components.mesh?.asset==='terrain'))throw Error('Unparent this actor before making it dynamic');if(path==='components.body.mass'&&value<=0)throw Error('Mass must be positive');if(typeof value==='number'&&(/(friction|restitution|radius|duration|roughness|metallic|emission|intensity|range|settings\.)/.test(path))&&value<0)throw Error('This parameter cannot be negative');if(path==='components.animation.duration'&&value<=0)throw Error('Animation duration must be positive');if(e?.components.mesh?.asset==='terrain'&&path.startsWith('transform.'))throw Error('Heightfield terrain stays at the world origin; use the sculpt tool');if(path.startsWith('@'))setPath(ed.scene.data.assets.materials[e.components.mesh.material],path.slice(1),value);else if(path.startsWith('!'))setPath(ed.scene.data,path.slice(1),value);else setPath(e,path,value);if(path.includes('.keys.'))for(const t of e.components.animation.tracks)t.keys.sort((a,b)=>a.time-b.time);});
  }
  click(event){const ed=this.editor,target=event.target.closest('button');if(!target)return;const e=ed.scene.get(ed.selection);if(target.dataset.removeComponent){ed.commit('Remove component',()=>{delete e.components[target.dataset.removeComponent];});return;}if(target.dataset.deleteKey!=null){ed.commit('Delete keyframe',()=>e.components.animation.tracks[ed.animationTrack||0].keys.splice(Number(target.dataset.deleteKey),1));return;}switch(target.dataset.inspectAction){case 'open-graph':ed.graphUI.graphId=e.components.graph.asset;ed.showBottom('graph');break;case 'terrain-tool':ed.setTool('terrain');break;case 'regenerate-terrain':ed.regenerateTerrain();break;case 'clear-preview':ed.previewScene=null;ed.previewTime=0;this.render();break;case 'add-component':{const type=$('#addComponentType').value;ed.commit('Add '+type,()=>{if(e.components[type])throw Error('This component already exists');if(type==='body')e.components.body={type:'static',shape:'box',mass:1,friction:.6,restitution:.1};if(type==='graph')e.components.graph={asset:Object.keys(ed.scene.data.assets.graphs)[0]};if(type==='animation')e.components.animation={duration:4,loop:true,tracks:[{property:'rotation.y',keys:[{time:0,value:e.transform.rotation[1]},{time:4,value:e.transform.rotation[1]+360}]}]};if(type==='light')e.components.light={type:'point',color:'#ffd4a3',intensity:5,range:12};if(type==='controller'){if(e.parent)throw Error('Player controller must be a world-root actor');for(const other of ed.scene.data.entities){delete other.components.player;delete other.components.controller;}e.components.controller={speed:6.5,jump:8.5};e.components.player={};e.components.body={type:'dynamic',shape:'box',mass:1,friction:0,restitution:0,velocity:[0,0,0]};}});break;}case 'add-key':ed.commit('Add keyframe',()=>{const a=e.components.animation,t=a.tracks[ed.animationTrack||0];if(!t)throw Error('Add a track first');const [p,axis]=t.property.split('.');t.keys.push({time:Math.min(a.duration,(t.keys.at(-1)?.time||0)+.5),value:e.transform[p]['xyz'.indexOf(axis)]});t.keys.sort((a,b)=>a.time-b.time);});break;case 'add-track':{const property=prompt('Track property: position.x/y/z, rotation.x/y/z, scale.x/y/z','position.y');if(!/^(position|rotation|scale)\.[xyz]$/.test(property||''))return;ed.commit('Add animation track',()=>{const [p,a]=property.split('.');e.components.animation.tracks.push({property,keys:[{time:0,value:e.transform[p]['xyz'.indexOf(a)]}]});ed.animationTrack=e.components.animation.tracks.length-1;});break;}}
  }
}
export class GraphUI {
  constructor(editor){this.editor=editor;this.graphId='pickup';this.pending=null;this.surface=$('#graphSurface');$('#graphSelect').onchange=e=>{this.graphId=e.target.value;this.render();};$('#nodeSelect').innerHTML=Object.entries(NODE_TYPES).map(([key,v])=>`<option value="${key}">${v.title}</option>`).join('');this.surface.addEventListener('click',e=>this.click(e));this.surface.addEventListener('change',e=>this.change(e));this.surface.addEventListener('pointerdown',e=>this.pointer(e));}
  get graph(){return this.editor.scene.data.assets.graphs[this.graphId];}
  render(){const graphs=this.editor.scene.data.assets.graphs;if(!graphs[this.graphId])this.graphId=Object.keys(graphs)[0];$('#graphSelect').innerHTML=Object.entries(graphs).map(([id,g])=>`<option value="${esc(id)}" ${id===this.graphId?'selected':''}>${esc(g.name)}</option>`).join('');const graph=this.graph;if(!graph){$('#graphNodes').innerHTML='';$('#graphWires').innerHTML='';return;}const colors={exec:'#d1dce4',number:'#99ca8c',boolean:'#e68a94'};
    $('#graphNodes').innerHTML=graph.nodes.map(n=>{const type=NODE_TYPES[n.type];if(!type)return '';const ports=(kind,definitions)=>Object.entries(definitions).map(([key,t])=>{const wired=graph.edges.some(e=>kind==='output'?e.from===n.id&&e.out===key:e.to===n.id&&e.in===key);return `<div class="node-port ${kind} ${t} ${wired?'wired':''}" data-node="${esc(n.id)}" data-port="${esc(key)}" data-kind="${kind}" style="--port-color:${colors[t]}">${kind==='input'?'<i class="port-dot"></i>':''}${esc(key)}${kind==='output'?'<i class="port-dot"></i>':''}</div>`;}).join('');return `<div class="graph-node ${type.category}" data-node="${esc(n.id)}" style="left:${Number(n.x)||0}px;top:${Number(n.y)||0}px"><div class="node-title">${icon(type.category==='event'?'play':type.category==='action'?'settings':'graph')} ${type.title}<button data-delete-node="${esc(n.id)}">×</button></div><div class="node-body"><div>${ports('input',type.inputs)}</div><div>${ports('output',type.outputs)}</div></div>${Object.keys(n.params).length?`<div class="node-params">${Object.entries(n.params).map(([k,v])=>`<label class="node-param">${esc(k)}${k==='axis'?`<select data-param="${esc(k)}" data-node="${esc(n.id)}">${['x','y','z'].map(a=>`<option ${a===v?'selected':''}>${a}</option>`).join('')}</select>`:`<input data-param="${esc(k)}" data-node="${esc(n.id)}" type="${typeof v==='number'?'number':typeof v==='boolean'?'checkbox':'text'}" ${typeof v==='boolean'?v?'checked':'':`value="${esc(v)}"`} step="0.1">`}</label>`).join('')}</div>`:''}</div>`;}).join('');requestAnimationFrame(()=>this.wires());this.pending=null;this.status();}
  wires(){if(!this.graph)return;const surface=this.surface.getBoundingClientRect(),find=(id,port,kind)=>[...this.surface.querySelectorAll('.node-port')].find(e=>e.dataset.node===id&&e.dataset.port===port&&e.dataset.kind===kind);$('#graphWires').innerHTML=this.graph.edges.map((edge,i)=>{const a=find(edge.from,edge.out,'output')?.querySelector('.port-dot')?.getBoundingClientRect(),b=find(edge.to,edge.in,'input')?.querySelector('.port-dot')?.getBoundingClientRect();if(!a||!b)return '';const x1=a.x+a.width/2-surface.x,y1=a.y+a.height/2-surface.y,x2=b.x+b.width/2-surface.x,y2=b.y+b.height/2-surface.y,dx=Math.max(70,Math.abs(x2-x1)*.5),type=NODE_TYPES[this.graph.nodes.find(n=>n.id===edge.from)?.type]?.outputs[edge.out],color=type==='exec'?'#c0cdd7':type==='number'?'#91ba86':'#d9808b';return `<path data-edge="${i}" stroke="${color}" d="M${x1} ${y1} C${x1+dx} ${y1},${x2-dx} ${y2},${x2} ${y2}"/>`;}).join('');}
  status(){const errors=validateGraph(this.graph);$('#graphStatus').textContent=errors.length?errors[0]:`${this.graph.nodes.length} nodes · ${this.graph.edges.length} wires · valid`;$('#graphStatus').style.color=errors.length?'#e69a8c':'';return errors;}
  click(event){const ed=this.editor;if(ed.runtime)return;const remove=event.target.closest('[data-delete-node]');if(remove){ed.commit('Delete graph node',()=>{const id=remove.dataset.deleteNode;this.graph.nodes=this.graph.nodes.filter(n=>n.id!==id);this.graph.edges=this.graph.edges.filter(e=>e.from!==id&&e.to!==id);});return;}if(event.target.dataset.edge!=null){ed.commit('Disconnect graph wire',()=>this.graph.edges.splice(Number(event.target.dataset.edge),1));return;}const port=event.target.closest('.node-port');if(!port)return;if(port.dataset.kind==='output'){this.pending={from:port.dataset.node,out:port.dataset.port};for(const p of this.surface.querySelectorAll('.connecting'))p.classList.remove('connecting');port.classList.add('connecting');ed.toast('Choose a compatible input port');}else if(this.pending){const edge={...this.pending,to:port.dataset.node,in:port.dataset.port};ed.commit('Connect graph wire',()=>{this.graph.edges=this.graph.edges.filter(e=>e.to!==edge.to||e.in!==edge.in);this.graph.edges.push(edge);const errors=validateGraph(this.graph);if(errors.length)throw Error(errors[0]);});}}
  change(event){const t=event.target;if(!t.dataset.param)return;this.editor.commit('Edit graph parameter',()=>{const n=this.graph.nodes.find(n=>n.id===t.dataset.node);n.params[t.dataset.param]=t.type==='number'?Number(t.value):t.type==='checkbox'?t.checked:t.value;});}
  pointer(event){const title=event.target.closest('.node-title');if(!title||event.target.closest('button')||this.editor.runtime)return;const element=title.closest('.graph-node'),node=this.graph.nodes.find(n=>n.id===element.dataset.node),before=this.editor.scene.serialize(),x=event.clientX,y=event.clientY,start=[node.x,node.y];title.setPointerCapture(event.pointerId);const move=e=>{node.x=Math.max(5,start[0]+e.clientX-x);node.y=Math.max(5,start[1]+e.clientY-y);element.style.left=node.x+'px';element.style.top=node.y+'px';this.wires();};const end=()=>{title.removeEventListener('pointermove',move);title.removeEventListener('pointerup',end);title.removeEventListener('pointercancel',end);this.editor.finishEdit(before,'Move graph node',false);};title.addEventListener('pointermove',move);title.addEventListener('pointerup',end);title.addEventListener('pointercancel',end);}
  addNode(){if(!this.graph)return;const type=$('#nodeSelect').value,viewport=$('#graphViewport');this.editor.commit('Add graph node',()=>this.graph.nodes.push(graphNode(type,uid('node'),viewport.scrollLeft+70+Math.random()*30,viewport.scrollTop+50+Math.random()*30)));}
}
