import {boundsTransform,vsub,vnorm,vdot,vmul,vadd,clamp} from './math.js';
import {terrainHeight} from './assets.js';
/** Uniform-grid broadphase; stable ID-sorted pair processing and translational impulses. */
export class SpatialHash {
  constructor(size=4){this.size=size;this.cells=new Map();this.global=[];}
  insert(item,bounds){const lo=bounds[0].map(x=>Math.floor(x/this.size)),hi=bounds[1].map(x=>Math.floor(x/this.size));if((hi[0]-lo[0]+1)*(hi[1]-lo[1]+1)*(hi[2]-lo[2]+1)>512){this.global.push(item);return;}for(let x=lo[0];x<=hi[0];x++)for(let y=lo[1];y<=hi[1];y++)for(let z=lo[2];z<=hi[2];z++){const k=`${x},${y},${z}`;if(!this.cells.has(k))this.cells.set(k,[]);this.cells.get(k).push(item);}}
  pairs(items){const pairs=new Map(),put=(a,b)=>{if(a.id===b.id||(!a.dynamic&&!b.dynamic))return;const [x,y]=a.id<b.id?[a,b]:[b,a];pairs.set(`${x.id}|${y.id}`,[x,y]);};for(const bucket of this.cells.values())for(let i=0;i<bucket.length;i++)for(let j=i+1;j<bucket.length;j++)put(bucket[i],bucket[j]);for(const a of this.global)for(const b of items)put(a,b);return [...pairs.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(x=>x[1]);}
}
export function collisionContact(a,b){
  if(a.shape==='sphere'&&b.shape==='sphere'){const d=vsub(a.center,b.center),l=Math.hypot(...d),p=a.radius+b.radius-l;return p>0?{normal:l>1e-8?vmul(d,1/l):[0,1,0],depth:p}:null;}
  if(a.shape==='sphere'||b.shape==='sphere'){const s=a.shape==='sphere'?a:b,box=s===a?b:a,p=s.center.map((v,k)=>clamp(v,box.bounds[0][k],box.bounds[1][k])),d=vsub(s.center,p),l=Math.hypot(...d);let n,depth;if(l>1e-8){depth=s.radius-l;if(depth<=0)return null;n=vmul(d,1/l);}else{let min=Infinity,axis=0,sign=1;for(let k=0;k<3;k++)for(const side of [0,1]){const dist=Math.abs(s.center[k]-box.bounds[side][k]);if(dist<min){min=dist;axis=k;sign=side?1:-1;}}n=[0,0,0];n[axis]=sign;depth=s.radius+min;}return {normal:s===a?n:vmul(n,-1),depth};}
  let depth=Infinity,axis=0;for(let k=0;k<3;k++){const p=Math.min(a.bounds[1][k],b.bounds[1][k])-Math.max(a.bounds[0][k],b.bounds[0][k]);if(p<=0)return null;if(p<depth){depth=p;axis=k;}}const normal=[0,0,0];normal[axis]=a.center[axis]>=b.center[axis]?1:-1;return {normal,depth};
}
export class PhysicsWorld {
  constructor(scene,assets){this.scene=scene;this.assets=assets;this.grounded=new Set();this.overlaps=new Set();this.stats={pairs:0,contacts:0};}
  colliders(){return this.scene.data.entities.filter(e=>e.components.body&&e.visible!==false&&e.components.mesh?.asset!=='terrain').sort((a,b)=>a.id.localeCompare(b.id)).map(e=>{const body=e.components.body,m=this.scene.world(e.id),local=body.halfExtents?[body.halfExtents.map(x=>-x),body.halfExtents]:this.assets.mesh(e.components.mesh?.asset||'cube').bounds,bounds=boundsTransform(local,m),center=bounds[0].map((v,k)=>(v+bounds[1][k])*.5),radius=(body.radius??.5)*Math.max(...e.transform.scale),shape=body.shape||'box';if(shape==='sphere'){bounds[0]=center.map(x=>x-radius);bounds[1]=center.map(x=>x+radius);}return {id:e.id,e,body,bounds,center,radius,shape,dynamic:body.type==='dynamic',trigger:!!body.trigger};});}
  step(dt){const scene=this.scene;this.grounded.clear();for(const e of scene.data.entities){const b=e.components.body;if(b?.type==='dynamic'){b.velocity??=[0,0,0];b.velocity[1]+=(b.gravity===false?0:-22)*dt;const damping=Math.exp(-(b.damping??.08)*dt);for(let k=0;k<3;k++){b.velocity[k]=clamp(b.velocity[k]*damping,-80,80);e.transform.position[k]+=b.velocity[k]*dt;}}}scene.invalidate();
    let colliders=this.colliders(),hash=new SpatialHash();for(const c of colliders)hash.insert(c,c.bounds);const pairs=hash.pairs(colliders),now=new Set(),events=[];this.stats={pairs:pairs.length,contacts:0};
    for(let pass=0;pass<4;pass++)for(const [a,b] of pairs){const c=collisionContact(a,b);if(!c)continue;if(pass===0){this.stats.contacts++;if(a.trigger||b.trigger){const key=`${a.id}|${b.id}`;now.add(key);if(!this.overlaps.has(key))events.push([a.e,b.e]);}}if(a.trigger||b.trigger)continue;const ia=a.dynamic?1/a.body.mass:0,ib=b.dynamic?1/b.body.mass:0,sum=ia+ib;if(!sum)continue;const n=c.normal,amount=Math.max(c.depth-.001,0)*.85/sum;const move=(o,s)=>{if(!o.dynamic)return;for(let k=0;k<3;k++){const d=n[k]*amount*s;o.e.transform.position[k]+=d;o.center[k]+=d;o.bounds[0][k]+=d;o.bounds[1][k]+=d;}};move(a,ia);move(b,-ib);
      if(a.dynamic&&n[1]>.5)this.grounded.add(a.id);if(b.dynamic&&n[1]<-.5)this.grounded.add(b.id);
      const va=a.body.velocity||[0,0,0],vb=b.body.velocity||[0,0,0],rel=vsub(va,vb),vn=vdot(rel,n);if(vn<0){const bounce=Math.min(a.body.restitution??.05,b.body.restitution??.05),j=-(1+(vn<-.5?bounce:0))*vn/sum;for(let k=0;k<3;k++){if(a.dynamic)va[k]+=n[k]*j*ia;if(b.dynamic)vb[k]-=n[k]*j*ib;}const tangent=vsub(rel,vmul(n,vn)),len=Math.hypot(...tangent);if(len>1e-6){const friction=Math.sqrt((a.body.friction??.6)*(b.body.friction??.6)),jt=Math.min(len/sum,j*friction),t=vmul(tangent,1/len);for(let k=0;k<3;k++){if(a.dynamic)va[k]-=t[k]*jt*ia;if(b.dynamic)vb[k]+=t[k]*jt*ib;}}}
    }
    const terrainEntity=scene.data.entities.find(e=>e.components.mesh?.asset==='terrain'&&e.visible!==false&&e.components.body);if(terrainEntity){const terrain=scene.data.assets.terrain;for(const c of colliders){if(!c.dynamic||c.trigger)continue;const floor=terrainHeight(terrain,c.center[0],c.center[2]),bottom=c.bounds[0][1];if(bottom<floor){c.e.transform.position[1]+=floor-bottom;const v=c.body.velocity;v[1]=Math.max(0,-v[1]*(c.body.restitution??0));v[0]*=Math.exp(-2*dt);v[2]*=Math.exp(-2*dt);this.grounded.add(c.id);}}}
    this.overlaps=now;scene.invalidate();return events;
  }
}
