import {mmul,lookAt,ortho,vnorm,vmul,vadd,point,inverse,hexRGB,frustumPlanes,inFrustum,boundsTransform} from './math.js';
const VERTEX_STRIDE=32,INSTANCE_STRIDE=144;
export const FORGE_WGSL=`
struct Frame { vp:mat4x4f, lightVP:mat4x4f, eye:vec4f, sun:vec4f, sunColor:vec4f, env:vec4f, points:array<vec4f,16> };
@group(0) @binding(0) var<uniform> frame:Frame;
@group(0) @binding(1) var shadowMap:texture_depth_2d;
@group(0) @binding(2) var shadowSampler:sampler_comparison;
@group(1) @binding(0) var colorMap:texture_2d<f32>;
@group(1) @binding(1) var colorSampler:sampler;
struct Vin { @location(0) p:vec3f, @location(1) n:vec3f, @location(2) uv:vec2f,
@location(3) m0:vec4f,@location(4) m1:vec4f,@location(5) m2:vec4f,@location(6) m3:vec4f,
@location(7) n0:vec4f,@location(8) n1:vec4f,@location(9) n2:vec4f,@location(10) color:vec4f,@location(11) material:vec4f };
struct Vout { @builtin(position) clip:vec4f,@location(0) world:vec3f,@location(1) normal:vec3f,@location(2) uv:vec2f,@location(3) @interpolate(flat) color:vec4f,@location(4) @interpolate(flat) material:vec4f };
@vertex fn vs(v:Vin)->Vout {var o:Vout;let model=mat4x4f(v.m0,v.m1,v.m2,v.m3);let w=model*vec4f(v.p,1);o.clip=frame.vp*w;o.world=w.xyz;o.normal=mat3x3f(v.n0.xyz,v.n1.xyz,v.n2.xyz)*v.n;o.uv=v.uv;o.color=v.color;o.material=v.material;return o;}
@vertex fn shadowVS(v:Vin)->@builtin(position) vec4f {return frame.lightVP*mat4x4f(v.m0,v.m1,v.m2,v.m3)*vec4f(v.p,1);}
fn fresnel(c:f32,f0:vec3f)->vec3f{return f0+(vec3f(1)-f0)*pow(clamp(1-c,0,1),5);}
fn brdf(n:vec3f,v:vec3f,l:vec3f,base:vec3f,rough:f32,metal:f32)->vec3f{
let h=normalize(v+l);let nl=max(dot(n,l),0.0);let nv=max(dot(n,v),0.001);let nh=max(dot(n,h),0.0);let vh=max(dot(v,h),0.0);let a=rough*rough;let a2=a*a;let d=a2/(3.14159265*pow(nh*nh*(a2-1)+1,2)+0.00001);let k=pow(rough+1,2)/8;let g=(nl/(nl*(1-k)+k))*(nv/(nv*(1-k)+k));let f=fresnel(vh,mix(vec3f(.04),base,metal));return ((vec3f(1)-f)*(1-metal)*base/3.14159265+d*g*f/(4*nl*nv+.0001))*nl;
}
fn visibility(p:vec3f,n:vec3f)->f32{let q=frame.lightVP*vec4f(p,1);let ndc=q.xyz/q.w;let uv=ndc.xy*vec2f(.5,-.5)+.5;if(any(uv<vec2f(0))||any(uv>vec2f(1))||ndc.z<0||ndc.z>1){return 1;}let bias=max(.00035*(1-dot(n,frame.sun.xyz)),.00012);var s=0.0;for(var y=-1;y<=1;y++){for(var x=-1;x<=1;x++){s+=textureSampleCompareLevel(shadowMap,shadowSampler,uv+vec2f(f32(x),f32(y))/2048.0,ndc.z-bias);}}return s/9;}
fn aces(x:vec3f)->vec3f{return clamp((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14),vec3f(0),vec3f(1));}
@fragment fn fs(i:Vout)->@location(0) vec4f{
let n=normalize(i.normal);let v=normalize(frame.eye.xyz-i.world);let tex=textureSample(colorMap,colorSampler,i.uv).rgb;var base=pow(i.color.rgb,vec3f(2.2))*tex;let rough=clamp(i.material.x,.045,1);let metal=clamp(i.material.y,0,1);let gridWidth=max(fwidth(i.world.xz*.5),vec2f(.001));
if((u32(round(i.material.w))&2u)!=0u){let q=abs(fract(i.world.xz*.5-.5)-.5)/gridWidth;let line=1-min(min(q.x,q.y),1);base=mix(base,base*1.65,line*.2);}
var color=base*frame.env.x*mix(.58,1.25,n.y*.5+.5)*(1-metal*.65);color+=brdf(n,v,frame.sun.xyz,base,rough,metal)*frame.sunColor.rgb*frame.sunColor.w*visibility(i.world,n);
for(var j=0;j<8;j++){if(f32(j)>=frame.env.w){break;}let p=frame.points[j*2];let c=frame.points[j*2+1];let d=p.xyz-i.world;let dist=length(d);let fall=pow(clamp(1-dist/p.w,0,1),2);color+=brdf(n,v,normalize(d),base,rough,metal)*c.rgb*c.w*fall/(1+dist*dist*.1);}
color+=base*i.material.z;if((u32(round(i.material.w))&1u)!=0u){color+=vec3f(.15,.65,.7)*pow(1-max(dot(n,v),0),3)*1.5;}
let distance=length(frame.eye.xyz-i.world);let fog=1-exp(-distance*frame.env.y);color=mix(color,vec3f(.22,.31,.38),clamp(fog,0,.8));return vec4f(pow(aces(color*frame.env.z),vec3f(1.0/2.2)),1);
}
struct SkyOut{@builtin(position) p:vec4f,@location(0) uv:vec2f};
@vertex fn skyVS(@builtin(vertex_index) id:u32)->SkyOut{var o:SkyOut;let p=vec2f(f32((id<<1u)&2u),f32(id&2u));o.uv=p;o.p=vec4f(p*2-1,.99999,1);return o;}
@fragment fn skyFS(i:SkyOut)->@location(0) vec4f{let y=clamp(i.uv.y,0,1);let col=mix(vec3f(.56,.62,.65),vec3f(.11,.20,.27),pow(y,.65));let glow=exp(-length((i.uv-vec2f(.73,.68))*vec2f(1,1.4))*5);return vec4f(col+vec3f(.15,.1,.035)*glow,1);}
`;
const GL_VERTEX=`#version 300 es
precision highp float;
layout(location=0) in vec3 aPos;layout(location=1) in vec3 aNormal;layout(location=2) in vec2 aUV;
layout(location=3) in vec4 m0;layout(location=4) in vec4 m1;layout(location=5) in vec4 m2;layout(location=6) in vec4 m3;
layout(location=7) in vec4 n0;layout(location=8) in vec4 n1;layout(location=9) in vec4 n2;layout(location=10) in vec4 aColor;layout(location=11) in vec4 aMaterial;
uniform mat4 uVP;out vec3 world;out vec3 normal;out vec2 uv;flat out vec4 color;flat out vec4 material;
void main(){vec4 w=mat4(m0,m1,m2,m3)*vec4(aPos,1);gl_Position=uVP*w;gl_Position.z=gl_Position.z*2.-gl_Position.w;world=w.xyz;normal=mat3(n0.xyz,n1.xyz,n2.xyz)*aNormal;uv=aUV;color=aColor;material=aMaterial;}`;
const GL_FRAGMENT=`#version 300 es
precision highp float;
in vec3 world;in vec3 normal;in vec2 uv;flat in vec4 color;flat in vec4 material;out vec4 frag;
uniform vec4 uEye,uSun,uSunColor,uEnv,uPoints[16];uniform mat4 uLightVP;uniform sampler2D uShadow,uTexture;
vec3 fresnel(float c,vec3 f0){return f0+(1.-f0)*pow(clamp(1.-c,0.,1.),5.);}
vec3 brdf(vec3 n,vec3 v,vec3 l,vec3 base,float rough,float metal){vec3 h=normalize(v+l);float nl=max(dot(n,l),0.),nv=max(dot(n,v),.001),nh=max(dot(n,h),0.),vh=max(dot(v,h),0.),a=rough*rough,a2=a*a,d=a2/(3.14159265*pow(nh*nh*(a2-1.)+1.,2.)+.00001),k=pow(rough+1.,2.)/8.,g=(nl/(nl*(1.-k)+k))*(nv/(nv*(1.-k)+k));vec3 f=fresnel(vh,mix(vec3(.04),base,metal));return ((1.-f)*(1.-metal)*base/3.14159265+d*g*f/(4.*nl*nv+.0001))*nl;}
float visibility(vec3 p,vec3 n){vec4 q=uLightVP*vec4(p,1);vec3 ndc=q.xyz/q.w;vec2 uv=ndc.xy*.5+.5;if(any(lessThan(uv,vec2(0)))||any(greaterThan(uv,vec2(1)))||ndc.z<0.||ndc.z>1.)return 1.;float bias=max(.00035*(1.-dot(n,uSun.xyz)),.00012),s=0.;for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++)s+=ndc.z-bias<=texture(uShadow,uv+vec2(x,y)/2048.).r?1.:0.;return s/9.;}
vec3 aces(vec3 x){return clamp((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14),0.,1.);}
void main(){vec3 n=normalize(normal),v=normalize(uEye.xyz-world),base=pow(color.rgb,vec3(2.2))*pow(texture(uTexture,uv).rgb,vec3(2.2));float rough=clamp(material.x,.045,1.),metal=clamp(material.y,0.,1.);if((int(round(material.w))&2)!=0){vec2 q=abs(fract(world.xz*.5-.5)-.5)/max(fwidth(world.xz*.5),vec2(.001));float line=1.-min(min(q.x,q.y),1.);base=mix(base,base*1.65,line*.2);}vec3 c=base*uEnv.x*mix(.58,1.25,n.y*.5+.5)*(1.-metal*.65)+brdf(n,v,uSun.xyz,base,rough,metal)*uSunColor.rgb*uSunColor.w*visibility(world,n);for(int j=0;j<8;j++){if(float(j)>=uEnv.w)break;vec4 p=uPoints[j*2],pc=uPoints[j*2+1];vec3 d=p.xyz-world;float dist=length(d),fall=pow(clamp(1.-dist/p.w,0.,1.),2.);c+=brdf(n,v,normalize(d),base,rough,metal)*pc.rgb*pc.w*fall/(1.+dist*dist*.1);}c+=base*material.z;if((int(round(material.w))&1)!=0)c+=vec3(.15,.65,.7)*pow(1.-max(dot(n,v),0.),3.)*1.5;float fog=1.-exp(-length(uEye.xyz-world)*uEnv.y);c=mix(c,vec3(.22,.31,.38),clamp(fog,0.,.8));frag=vec4(pow(aces(c*uEnv.z),vec3(1./2.2)),1);}`;
const GL_SKY_V=`#version 300 es
precision highp float;out vec2 uv;void main(){vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));uv=p;gl_Position=vec4(p*2.-1.,.99999,1);}`;
const GL_SKY_F=`#version 300 es
precision highp float;in vec2 uv;out vec4 frag;void main(){float y=clamp(uv.y,0.,1.);vec3 c=mix(vec3(.56,.62,.65),vec3(.11,.20,.27),pow(y,.65));float glow=exp(-length((uv-vec2(.73,.68))*vec2(1,1.4))*5.);frag=vec4(c+vec3(.15,.1,.035)*glow,1);}`;
export class GPUBackend {
  async init(canvas,onError){
    if(!navigator.gpu)throw Error('WebGPU is not exposed by this browser');const adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!adapter)throw Error('No WebGPU adapter');this.device=await adapter.requestDevice();const d=this.device;this.onError=onError;d.addEventListener('uncapturederror',e=>onError(e.error.message));d.lost.then(info=>onError(`GPU device lost: ${info.message}. Reload to restore the device.`));this.canvas=canvas;this.context=canvas.getContext('webgpu');this.format=navigator.gpu.getPreferredCanvasFormat();this.context.configure({device:d,format:this.format,alphaMode:'opaque'});
    const module=d.createShaderModule({label:'Vanta PBR / shadow / sky',code:FORGE_WGSL});const messages=(await module.getCompilationInfo()).messages.filter(m=>m.type==='error');if(messages.length)throw Error(messages.map(m=>`${m.lineNum}: ${m.message}`).join('\n'));
    this.frameBuffer=d.createBuffer({size:448,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});
    this.frameLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}},{binding:1,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'depth'}},{binding:2,visibility:GPUShaderStage.FRAGMENT,sampler:{type:'comparison'}}]});
    this.textureLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'float'}},{binding:1,visibility:GPUShaderStage.FRAGMENT,sampler:{type:'filtering'}}]});
    this.shadowLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.VERTEX,buffer:{type:'uniform'}}]});
    this.shadow=d.createTexture({label:'2048 PCF shadow map',size:[2048,2048],format:'depth32float',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING});this.shadowView=this.shadow.createView();
    this.shadowSampler=d.createSampler({compare:'less-equal',magFilter:'linear',minFilter:'linear'});this.textureSampler=d.createSampler({magFilter:'linear',minFilter:'linear',addressModeU:'repeat',addressModeV:'repeat'});
    this.frameGroup=d.createBindGroup({layout:this.frameLayout,entries:[{binding:0,resource:{buffer:this.frameBuffer}},{binding:1,resource:this.shadowView},{binding:2,resource:this.shadowSampler}]});this.shadowGroup=d.createBindGroup({layout:this.shadowLayout,entries:[{binding:0,resource:{buffer:this.frameBuffer}}]});
    const buffers=[{arrayStride:32,attributes:[{shaderLocation:0,offset:0,format:'float32x3'},{shaderLocation:1,offset:12,format:'float32x3'},{shaderLocation:2,offset:24,format:'float32x2'}]},{arrayStride:144,stepMode:'instance',attributes:Array.from({length:9},(_,i)=>({shaderLocation:i+3,offset:i*16,format:'float32x4'}))}];
    const layout=d.createPipelineLayout({bindGroupLayouts:[this.frameLayout,this.textureLayout]});
    this.main=await d.createRenderPipelineAsync({label:'GGX metallic/roughness instanced',layout,vertex:{module,entryPoint:'vs',buffers},fragment:{module,entryPoint:'fs',targets:[{format:this.format}]},primitive:{topology:'triangle-list',cullMode:'back'},depthStencil:{format:'depth24plus',depthWriteEnabled:true,depthCompare:'less'},multisample:{count:4}});
    this.shadowPipeline=await d.createRenderPipelineAsync({label:'Directional shadow depth',layout:d.createPipelineLayout({bindGroupLayouts:[this.shadowLayout]}),vertex:{module,entryPoint:'shadowVS',buffers},primitive:{topology:'triangle-list',cullMode:'back'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less',depthBias:2,depthBiasSlopeScale:2}});
    this.sky=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[]}),vertex:{module,entryPoint:'skyVS'},fragment:{module,entryPoint:'skyFS',targets:[{format:this.format}]},primitive:{topology:'triangle-list'},depthStencil:{format:'depth24plus',depthWriteEnabled:false,depthCompare:'always'},multisample:{count:4}});
    this.meshes=new Map();this.instances=new Map();this.textures=new Map();this.white=this.makeTexture(new Uint8Array([255,255,255,255]),1,1);return 'WebGPU';
  }
  makeTexture(data,w,h){const d=this.device,t=d.createTexture({size:[w,h],format:'rgba8unorm-srgb',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST|GPUTextureUsage.RENDER_ATTACHMENT});if(data instanceof Uint8Array)d.queue.writeTexture({texture:t},data,{bytesPerRow:w*4},[w,h]);else d.queue.copyExternalImageToTexture({source:data},{texture:t},[w,h]);return {texture:t,group:d.createBindGroup({layout:this.textureLayout,entries:[{binding:0,resource:t.createView()},{binding:1,resource:this.textureSampler}]})};}
  texture(material){const key=material.texture;if(!key)return this.white.group;const old=this.textures.get(key);if(old)return old.group||this.white.group;this.textures.set(key,{pending:true});fetch(key).then(r=>r.blob()).then(b=>createImageBitmap(b)).then(image=>{this.textures.set(key,this.makeTexture(image,image.width,image.height));image.close();}).catch(e=>{this.onError(`Texture: ${e.message}`);this.textures.set(key,this.white);});return this.white.group;}
  mesh(mesh){let old=this.meshes.get(mesh);if(old)return old;const d=this.device,v=d.createBuffer({size:mesh.vertices.byteLength,usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST}),i=d.createBuffer({size:mesh.indices.byteLength,usage:GPUBufferUsage.INDEX|GPUBufferUsage.COPY_DST});d.queue.writeBuffer(v,0,mesh.vertices);d.queue.writeBuffer(i,0,mesh.indices);old={v,i,count:mesh.indices.length,last:this.frame};this.meshes.set(mesh,old);return old;}
  resize(w,h){if(this.width===w&&this.height===h)return;this.width=w;this.height=h;this.canvas.width=w;this.canvas.height=h;this.depth?.destroy();this.color?.destroy();this.depth=this.device.createTexture({size:[w,h],sampleCount:4,format:'depth24plus',usage:GPUTextureUsage.RENDER_ATTACHMENT});this.color=this.device.createTexture({size:[w,h],sampleCount:4,format:this.format,usage:GPUTextureUsage.RENDER_ATTACHMENT});}
  draw(frame,main,shadow,w,h){this.frame=(this.frame||0)+1;this.resize(w,h);const d=this.device;d.queue.writeBuffer(this.frameBuffer,0,frame);const prepare=(groups,prefix)=>groups.map(g=>{const key=prefix+g.key;let b=this.instances.get(key);if(!b||b.capacity<g.data.byteLength){b?.buffer.destroy();const capacity=2**Math.ceil(Math.log2(Math.max(144,g.data.byteLength)));b={buffer:d.createBuffer({size:capacity,usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST}),capacity};this.instances.set(key,b);}b.last=this.frame;d.queue.writeBuffer(b.buffer,0,g.data);const mesh=this.mesh(g.mesh);mesh.last=this.frame;return {...g,buffer:b.buffer,gpu:mesh,texture:this.texture(g.material)};});const sm=prepare(shadow,'S'),mn=prepare(main,'M');
    const encoder=d.createCommandEncoder();let pass=encoder.beginRenderPass({label:'Shadow pass',colorAttachments:[],depthStencilAttachment:{view:this.shadowView,depthClearValue:1,depthLoadOp:'clear',depthStoreOp:'store'}});pass.setPipeline(this.shadowPipeline);pass.setBindGroup(0,this.shadowGroup);for(const g of sm){pass.setVertexBuffer(0,g.gpu.v);pass.setVertexBuffer(1,g.buffer);pass.setIndexBuffer(g.gpu.i,'uint32');pass.drawIndexed(g.gpu.count,g.count);}pass.end();
    pass=encoder.beginRenderPass({label:'Forward PBR + sky',colorAttachments:[{view:this.color.createView(),resolveTarget:this.context.getCurrentTexture().createView(),clearValue:{r:.12,g:.2,b:.26,a:1},loadOp:'clear',storeOp:'discard'}],depthStencilAttachment:{view:this.depth.createView(),depthClearValue:1,depthLoadOp:'clear',depthStoreOp:'discard'}});pass.setPipeline(this.sky);pass.draw(3);pass.setPipeline(this.main);pass.setBindGroup(0,this.frameGroup);for(const g of mn){pass.setBindGroup(1,g.texture);pass.setVertexBuffer(0,g.gpu.v);pass.setVertexBuffer(1,g.buffer);pass.setIndexBuffer(g.gpu.i,'uint32');pass.drawIndexed(g.gpu.count,g.count);}pass.end();d.queue.submit([encoder.finish()]);
    if(this.frame%240===0){for(const [k,b] of this.instances)if(this.frame-b.last>240){b.buffer.destroy();this.instances.delete(k);}for(const [k,b] of this.meshes)if(this.frame-b.last>240){b.v.destroy();b.i.destroy();this.meshes.delete(k);}}
  }
  dispose(){this.device?.destroy();}
}
export class GLBackend {
  async init(canvas,onError){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!this.gl)throw Error('Neither WebGPU nor WebGL2 is available');this.onError=onError;const gl=this.gl;this.main=this.program(GL_VERTEX,GL_FRAGMENT);this.shadowProgram=this.program(GL_VERTEX,'#version 300 es\nprecision highp float;void main(){}');this.sky=this.program(GL_SKY_V,GL_SKY_F);this.frame=0;this.meshes=new Map();this.instances=new Map();this.textures=new Map();this.white=this.makeTexture(new Uint8Array([255,255,255,255]),1,1);
    this.shadow=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.shadow);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,2048,2048,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);this.shadowFBO=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowFBO);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,this.shadow,0);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Shadow framebuffer incomplete');gl.bindFramebuffer(gl.FRAMEBUFFER,null);return 'WebGL2 fallback';
  }
  program(vs,fs){const gl=this.gl,p=gl.createProgram();for(const [type,source] of [[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);gl.deleteShader(s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return {p,u:new Map()};}
  uniform(p,name){if(!p.u.has(name))p.u.set(name,this.gl.getUniformLocation(p.p,name));return p.u.get(name);}
  makeTexture(data,w,h){const gl=this.gl,t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);if(data instanceof Uint8Array)gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,w,h,0,gl.RGBA,gl.UNSIGNED_BYTE,data);else gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,data);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT);return t;}
  texture(m){if(!m.texture)return this.white;if(this.textures.has(m.texture))return this.textures.get(m.texture)||this.white;this.textures.set(m.texture,null);const image=new Image();image.onload=()=>this.textures.set(m.texture,this.makeTexture(image));image.onerror=()=>this.onError('Texture decoding failed');image.src=m.texture;return this.white;}
  mesh(mesh){if(this.meshes.has(mesh)){const result=this.meshes.get(mesh);result.last=this.frame;return result;}const gl=this.gl,v=gl.createBuffer(),i=gl.createBuffer(),vao=gl.createVertexArray();gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,v);gl.bufferData(gl.ARRAY_BUFFER,mesh.vertices,gl.STATIC_DRAW);for(const [loc,size,offset] of [[0,3,0],[1,3,12],[2,2,24]]){gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,32,offset);}gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,i);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,mesh.indices,gl.STATIC_DRAW);const result={v,i,vao,count:mesh.indices.length,last:this.frame};this.meshes.set(mesh,result);return result;}
  draw(frame,main,shadow,w,h){this.frame++;const gl=this.gl;if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}const drawGroups=(groups,program,prefix)=>{gl.useProgram(program.p);for(const g of groups){const mesh=this.mesh(g.mesh),key=prefix+g.key;let instance=this.instances.get(key);if(!instance){instance={buffer:gl.createBuffer(),last:this.frame};this.instances.set(key,instance);}instance.last=this.frame;gl.bindVertexArray(mesh.vao);gl.bindBuffer(gl.ARRAY_BUFFER,instance.buffer);gl.bufferData(gl.ARRAY_BUFFER,g.data,gl.DYNAMIC_DRAW);for(let i=0;i<9;i++){gl.enableVertexAttribArray(i+3);gl.vertexAttribPointer(i+3,4,gl.FLOAT,false,144,i*16);gl.vertexAttribDivisor(i+3,1);}if(program===this.main){gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,this.texture(g.material));}gl.drawElementsInstanced(gl.TRIANGLES,mesh.count,gl.UNSIGNED_INT,0,g.count);}};
    gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);gl.bindFramebuffer(gl.FRAMEBUFFER,this.shadowFBO);gl.viewport(0,0,2048,2048);gl.clear(gl.DEPTH_BUFFER_BIT);gl.useProgram(this.shadowProgram.p);gl.uniformMatrix4fv(this.uniform(this.shadowProgram,'uVP'),false,frame.subarray(16,32));gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(2,2);drawGroups(shadow,this.shadowProgram,'S');gl.disable(gl.POLYGON_OFFSET_FILL);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,w,h);gl.clearColor(.12,.2,.26,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.disable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.bindVertexArray(null);gl.useProgram(this.sky.p);gl.drawArrays(gl.TRIANGLES,0,3);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);
    const p=this.main;gl.useProgram(p.p);gl.uniformMatrix4fv(this.uniform(p,'uVP'),false,frame.subarray(0,16));gl.uniformMatrix4fv(this.uniform(p,'uLightVP'),false,frame.subarray(16,32));for(const [name,offset] of [['uEye',32],['uSun',36],['uSunColor',40],['uEnv',44]])gl.uniform4fv(this.uniform(p,name),frame.subarray(offset,offset+4));gl.uniform4fv(this.uniform(p,'uPoints[0]'),frame.subarray(48,112));gl.uniform1i(this.uniform(p,'uShadow'),0);gl.uniform1i(this.uniform(p,'uTexture'),1);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.shadow);drawGroups(main,p,'M');gl.bindVertexArray(null);if(this.frame%240===0){for(const [key,m] of this.meshes)if(this.frame-m.last>240){gl.deleteBuffer(m.v);gl.deleteBuffer(m.i);gl.deleteVertexArray(m.vao);this.meshes.delete(key);}for(const [key,i] of this.instances)if(this.frame-i.last>240){gl.deleteBuffer(i.buffer);this.instances.delete(key);}}
  }
  dispose(){this.gl?.getExtension('WEBGL_lose_context')?.loseContext();}
}
export class Renderer {
  constructor(canvas,onError=console.error){this.canvas=canvas;this.onError=onError;this.stats={draws:0,triangles:0,visible:0,total:0};}
  async init(forceGL=false){if(!forceGL){try{this.backend=new GPUBackend();this.name=await this.backend.init(this.canvas,this.onError);return;}catch(e){this.onError(`WebGPU: ${e.message}`);this.backend?.dispose();if(this.canvas.getContext('webgpu')){const old=this.canvas,replacement=old.cloneNode();old.replaceWith(replacement);this.canvas=replacement;}}}this.backend=new GLBackend();this.name=await this.backend.init(this.canvas,this.onError);}
  render(scene,assets,camera,selection=null){const rect=this.canvas.getBoundingClientRect(),ratio=Math.min(window.devicePixelRatio||1,2),w=Math.max(1,Math.floor(rect.width*ratio)),h=Math.max(1,Math.floor(rect.height*ratio));if(!rect.width||!rect.height)return;
    const vp=mmul(camera.projection(rect.width/rect.height),lookAt(camera.eye,camera.target)),planes=frustumPlanes(vp),settings=scene.data.settings||{},sunEntity=scene.data.entities.find(e=>e.components.light?.type==='directional'&&e.visible!==false),sun=sunEntity?.components.light||{direction:[-.5,.85,.3],color:'#ffebcc',intensity:4},sunDir=vnorm(sun.direction||[-.5,.85,.3]),lightTarget=[camera.target[0],0,camera.target[2]],lightVP=mmul(ortho(-36,36,-36,36,.1,140),lookAt(vadd(lightTarget,vmul(sunDir,65)),lightTarget)),lightPlanes=frustumPlanes(lightVP),frame=new Float32Array(112);frame.set(vp);frame.set(lightVP,16);frame.set([...camera.eye,1],32);frame.set([...sunDir,0],36);frame.set([...hexRGB(sun.color),sun.intensity],40);
    const pointLights=scene.data.entities.filter(e=>e.components.light?.type==='point'&&e.visible!==false).slice(0,8);frame.set([settings.ambient??.45,settings.fog??.008,settings.exposure??1.15,pointLights.length],44);pointLights.forEach((e,i)=>{const l=e.components.light;frame.set([...point(scene.world(e.id),[0,0,0]),l.range||12],48+i*8);frame.set([...hexRGB(l.color),l.intensity],52+i*8);});
    const main=new Map(),shadow=new Map();let visible=0,total=0,triangles=0;const add=(map,e,mesh,matrix,material)=>{const key=e.components.mesh.asset+'|'+e.components.mesh.material;let group=map.get(key);if(!group){group={key,mesh,material,records:[]};map.set(key,group);}const inv=inverse(matrix),record=new Float32Array(36);record.set(matrix);if(inv)for(let c=0;c<3;c++)record.set([inv[c],inv[c+4],inv[c+8],0],16+c*4);record.set([...hexRGB(material.color),1],28);record.set([material.roughness,material.metallic,material.emission,(e.id===selection?1:0)+(material.grid?2:0)],32);group.records.push(record);};
    for(const e of scene.data.entities){const component=e.components.mesh;if(!component||e.visible===false)continue;let parent=e.parent,hidden=false;while(parent){const p=scene.get(parent);if(!p)break;if(p.visible===false){hidden=true;break;}parent=p.parent;}if(hidden)continue;total++;const mesh=assets.mesh(component.asset),matrix=scene.world(e.id),bounds=boundsTransform(mesh.bounds,matrix),material=scene.data.assets.materials[component.material]||scene.data.assets.materials.stone;if(inFrustum(bounds,planes)){add(main,e,mesh,matrix,material);visible++;triangles+=mesh.indices.length/3;}if(component.castShadow!==false&&inFrustum(bounds,lightPlanes))add(shadow,e,mesh,matrix,material);}
    const pack=map=>[...map.values()].map(g=>{const data=new Float32Array(g.records.length*36);g.records.forEach((r,i)=>data.set(r,i*36));return {key:g.key,mesh:g.mesh,material:g.material,data,count:g.records.length};});const mg=pack(main),sg=pack(shadow);this.backend.draw(frame,mg,sg,w,h);this.vp=vp;this.stats={draws:mg.length+sg.length+1,mainDraws:mg.length,triangles,visible,total,instances:visible};return vp;
  }
}
